Latest

diff --git a/roles/misc/nexus3-oss/.config/taskfiles/ansible/Taskfile-playbook.yml b/roles/misc/nexus3-oss/.config/taskfiles/ansible/Taskfile-playbook.yml
--- a/roles/misc/nexus3-oss/.config/taskfiles/ansible/Taskfile-playbook.yml
+++ b/roles/misc/nexus3-oss/.config/taskfiles/ansible/Taskfile-playbook.yml
@@ -2,7 +2,87 @@
 version: '3'
 
 tasks:
+  collections:download:
+    cmds:
+      - |
+        PATH="$PATH:$HOME/.local/bin"
+        ansible-galaxy collection download -r requirements.yml
+
   docs:
+    deps:
+      - docs:roles
+      - docs:tags
+
+  docs:roles:
+    deps:
+      - :install:software:jq
+      - :install:software:yq
+    log:
+      error: Failed to acquire README chart data for the roles
+      start: Scanning roles folder and generating chart data
+      success: Finished populating roles folder chart data
+    cmds:
+      - |
+        TMP="$(mktemp)"
+        jq --arg name "Role Name" --arg description "Description" --arg github 'GitHub&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;' \
+        '.role_var_chart = [[$name, $description, $github]]' .variables.json > "$TMP"
+        mv "$TMP" .variables.json
+        for ROLE_PATH in roles/*/*; do
+          if [[ "$ROLE_PATH" != *"roles/deprecated/"* ]] && [[ "$ROLE_PATH" != *"roles/cloud/"* ]] && [[ "$ROLE_PATH" != *"roles/helpers/"* ]]; then
+            if [ "$(yq e '.galaxy_info.project.documentation' "${ROLE_PATH}/meta/main.yml")" != 'null' ]; then
+              DOCUMENTATION_LINK="*[Documentation]($(yq e '.galaxy_info.project.documentation' "${ROLE_PATH}/meta/main.yml" | sed 's/null//'))* | "
+            else
+              DOCUMENTATION_LINK=""
+            fi
+            if [ "$(yq e '.galaxy_info.project.homepage' "${ROLE_PATH}/meta/main.yml")" != 'null' ]; then
+              HOMEPAGE_LINK="*[Homepage]($(yq e '.galaxy_info.project.homepage' "${ROLE_PATH}/meta/main.yml"))* | "
+            else
+              HOMEPAGE_LINK=""
+            fi
+            GITHUB_URL="$(yq e '.galaxy_info.project.github' "${ROLE_PATH}/meta/main.yml")"
+            if [ "$GITHUB_URL" == 'Not open-source' ]; then
+              GITHUB_SHIELD="**❌ Closed source**"
+            elif [ "$GITHUB_URL" != 'null' ]; then
+              GITHUB_PATH="$(echo "$GITHUB_URL" | sed 's/https:\/\/github.com\///' | sed 's/\/$//')"
+              GITHUB_OWNER="$(echo "$GITHUB_PATH" | sed 's/\/.*$//')"
+              GITHUB_PROJECT_SLUG="$(echo "$GITHUB_PATH" | sed 's/^.*\///')"
+              GITHUB_SHIELD="[![GitHub Repo stars](https://img.shields.io/github/stars/$GITHUB_OWNER/$GITHUB_PROJECT_SLUG?style=social)]($GITHUB_URL)"
+            else
+              UPSTREAM_URL="$(yq e '.galaxy_info.project.upstream' "${ROLE_PATH}/meta/main.yml")"
+              if [ "$UPSTREAM_URL" != 'null' ]; then
+                GITHUB_SHIELD="**[✅ Open-source]($UPSTREAM_URL)**"
+              else
+                GITHUB_SHIELD="*N/A*"
+              fi
+            fi
+            SOFTWARE_NAME="$(jq -r '.blueprint.name' "${ROLE_PATH}/package.json")"
+            DESCRIPTION="$(jq -r '.blueprint.overview' "${ROLE_PATH}/package.json")"
+            ROLE_GITHUB_LINK="*[Role on GitHub]($(jq -r '.blueprint.repository.github' "${ROLE_PATH}/package.json"))*"
+            ANSIBLE_GALAXY_NAMESPACE="$(yq e '.galaxy_info.namespace' "${ROLE_PATH}/meta/main.yml")"
+            ANSIBLE_GALAXY_ROLE_NAME="$(yq e '.galaxy_info.role_name' "${ROLE_PATH}/meta/main.yml")"
+            ROLE_ANSIBLE_GALAXY_URL="https://galaxy.ansible.com/${ANSIBLE_GALAXY_NAMESPACE}/${ANSIBLE_GALAXY_ROLE_NAME}"
+            if [ "$ANSIBLE_GALAXY_NAMESPACE" != 'null' ] && [ "$ANSIBLE_GALAXY_ROLE_NAME" != 'null' ]; then
+              URL_LINK="**[${SOFTWARE_NAME}](${ROLE_ANSIBLE_GALAXY_URL})**"
+            else
+              URL_LINK="**${SOFTWARE_NAME}**"
+            fi
+            if [ "$(jq -r '.blueprint.ansible_galaxy_project_id' "${ROLE_PATH}/package.json")" == 'null' ]; then
+              ROLE_GITHUB_LINK=""
+            fi
+            DESCRIPTION_LINKS="(${HOMEPAGE_LINK}${DOCUMENTATION_LINK}${ROLE_GITHUB_LINK})"
+            if [ "$DESCRIPTION_LINKS" != "()" ]; then
+              DESCRIPTION_LINKS=" $(echo "$DESCRIPTION_LINKS" | sed 's/ | )$/)/')"
+            else
+              DESCRIPTION_LINKS=""
+            fi
+            TMP="$(mktemp)"
+            jq --arg name "${URL_LINK}" --arg description "${DESCRIPTION}${DESCRIPTION_LINKS}" --arg github "${GITHUB_SHIELD}" \
+            '.role_var_chart = .role_var_chart + [[$name, $description, $github]]' .variables.json > "$TMP"
+            mv "$TMP" .variables.json
+          fi
+        done
+
+  docs:tags:
     deps:
       - :install:npm:leasot
     summary: |
@@ -16,7 +96,7 @@ tasks:
       }
       ```
     vars:
-      DOC_IDS: '@binary,@brew,@cask,@chrome,@firefox,@gem,@helm,@npm,@pypi,@vscode'
+      DOC_IDS: '@binaryapp,@binarycli,@brew,@cask,@chrome,@firefox,@gem,@helm,@npm,@pypi,@vscode'
     log:
       error: Failed to acquire package information from comments via `leasot`
       start: Scanning and acquiring package information in comments via `leasot`
@@ -24,15 +104,47 @@ tasks:
     cmds:
       - |
         function populateChartVar() {
-          CHART='[["Package", "Description"]'
+          CHART='[["Package", "Description", "GitHub&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"]'
           jq --arg tag "$(echo $2 | tr '[a-z]' '[A-Z]')" -r '.[] | select(.tag == $tag) | .
           | del(. ["file", "ref", "line", "tag"]) | .text' "$1" | while read COMMENT; do
             if [ "$CHART" != '[' ]; then
               CHART="${CHART},"
             fi
             LINK="$(echo $COMMENT | sed 's/ - .*//')"
+            URL_LINK="$(echo "$LINK" | sed 's/@tui //' | sed 's/@service //' | sed 's/@binary //' | sed 's/@cli //' | sed 's/@application //' | sed 's/@menubar //' | sed 's/@webapp //' | sed 's/^\[\([^)]*\)\](\([^)]*\)).*$/\[\1\](\2)/' | sed 's/ $//' | sed 's/\/$//')"
+            if [[ "$LINK" == *"[GitHub](NO_GITHUB_REPOSITORY_LINK)"* ]] || [[ "$LINK" != *"https://github.com"* ]]; then
+              GITHUB_SHIELD="*N/A*"
+            else
+              GITHUB_PATH="$(echo "$LINK" | sed 's/.*\[GitHub\](https:\/\/github.com\/\([^|]*\)).*/\1/' | \
+              sed 's/.*\[.*\](https:\/\/github.com\/\([^)]*\)).*/\1/' | sed 's/\/$//')"
+              GITHUB_OWNER="$(echo "$GITHUB_PATH" | sed 's/\/.*$//')"
+              GITHUB_PROJECT_SLUG="$(echo "$GITHUB_PATH" | sed 's/^.*\///')"
+              GITHUB_URL="https://github.com/${GITHUB_OWNER}/${GITHUB_PROJECT_SLUG}"
+              GITHUB_SHIELD="[![GitHub Repo stars](https://img.shields.io/github/stars/$GITHUB_OWNER/$GITHUB_PROJECT_SLUG?style=social)]($GITHUB_URL)"
+            fi
+            if [[ "$LINK" == *"[Documentation]"* ]]; then
+              DOCUMENTATION_LINK="*[Documentation]("$(echo "$LINK" | sed 's/.*\[Documentation\](\([^)]*\)).*/\1/')")* | "
+            else
+              DOCUMENTATION_LINK=""
+            fi
+            if [[ "$LINK" == *"[Homepage]"* ]]; then
+              HOMEPAGE_LINK="*[Homepage]("$(echo "$LINK" | sed 's/.*\[Homepage\](\([^)]*\)).*/\1/' | sed 's/ $//')")* | "
+            else
+              HOMEPAGE_LINK=""
+            fi
+            if [[ "$LINK" == *"[Helm]"* ]] || [[ "$LINK" == *"[Operator]"* ]]; then
+              REFERENCE_LINK="*[Helm Reference]("$(echo "$LINK" | sed 's/.*\[Helm\](\([^)]*\)).*/\1/' | sed 's/.*\[Operator\](\([^)]*\)).*/\1/')")* | "
+            else
+              REFERENCE_LINK=""
+            fi
+            DESCRIPTION_LINKS="(${HOMEPAGE_LINK}${DOCUMENTATION_LINK}${REFERENCE_LINK})"
+            if [ "$DESCRIPTION_LINKS" != "()" ]; then
+              DESCRIPTION_LINKS=" $(echo "$DESCRIPTION_LINKS" | sed 's/ | )$/)/')"
+            else
+              DESCRIPTION_LINKS=""
+            fi
             DESCRIPTION="$(echo $COMMENT | sed 's/.* - //' | sed 's/\"/\\\"/g')"
-            CHART="${CHART}[\"**$LINK**\",\"$DESCRIPTION\"]"
+            CHART="${CHART}[\"**$URL_LINK**\",\"${DESCRIPTION}${DESCRIPTION_LINKS}\",\"$GITHUB_SHIELD\"]"
           done
           CHART="${CHART}]"
           TMP_CHART="$(mktemp)"
@@ -79,7 +191,7 @@ tasks:
             if test -L "$ITEM" || ! test -e "$ITEM"; then
               rm -f "$ITEM"
               ln -s "./environments/{{.CLI_ARGS}}/$ITEM" "$ITEM"
-              .config/log success "Successfully symlinked `$ITEM` from ./environments/{{.CLI_ARGS}}/$ITEM"
+              .config/log success "Successfully symlinked "'`'"$ITEM"'`'" from ./environments/{{.CLI_ARGS}}/$ITEM"
             else
               .config/log warn "$ITEM exists in the root and was not a symlink so it was skipped to prevent possible data loss"
             fi
@@ -87,9 +199,10 @@ tasks:
         {{else}}
           exit 69
         {{end}}
+      - .config/log finish 'Success `environment:cli`'
 
   environment:prompt:
-    vars:
+    env:
       MARKDOWN: |
         # Symlink Environment
 
@@ -102,30 +215,24 @@ tasks:
         symlink all of the items in the environments folder to the root as long as there
         is not anything except a symlink to the target location (i.e. it will overwrite
         symlinks but not files).
+
     cmds:
-      - task: :log:markdown
-        vars:
-          MARKDOWN: '{{.MARKDOWN}}'
+      - TMP="$(mktemp)" && echo "$MARKDOWN" > "$TMP" && .config/log md "$TMP"
       - task: environment:prompt:continue
 
   environment:prompt:continue:
     interactive: true
     deps:
+      - :install:software:gum
       - :install:software:jq
-    vars:
-      ENVIRONMENT_OPTIONS:
-        sh: find ./environments -maxdepth 1 -mindepth 1 | sed 's/\.\/environments\///' | jq -R '[.]' | jq -s -c 'add'
-    prompt:
-      type: select
-      message: Which environment would you like to use?
-      options: '{{.ENVIRONMENT_OPTIONS}}'
-      answer:
-        cmds:
-          - task: environment:cli
-            vars:
-              CLI_ARGS: '{{.ANSWER}}'
+    cmds:
+      - |
+        ENVIRONMENT_OPTIONS="$(find ./environments -maxdepth 1 -mindepth 1 | sed 's/\.\/environments\///' | jq -R '[.]' | jq -s -c -r 'add | join(" ")')"
+        .config/log prompt 'Select an environment from the `environments/` folder to symlink to'
+        ENV_OPTION="$(gum choose $(echo $ENVIRONMENT_OPTIONS))"
+        task ansible:playbook:environment:cli -- "$ENV_OPTION"
 
-  find-missing:
+  find-missing:files:
     desc: Find roles that are missing files
     hide: '{{ne (print .REPOSITORY_TYPE "-" .REPOSITORY_SUBTYPE) "ansible-playbook"}}'
     summary: |
@@ -151,6 +258,35 @@ tasks:
     preconditions:
       - sh: test -d roles
         msg: The `roles/` folder is missing. Is the project set up right?
+
+  find-missing:roles:
+    summary: |
+      # Find roles that are not in main.yml
+
+      This task will collect all the role paths in the `roles/` folder and return a list
+      of roles that are not present in the `main.yml` file.
+
+      If you want to scan something other than `main.yml`, you can pass the file in as a
+      CLI argument like so:
+
+      **Example scanning file other than `main.yml`:**
+      `task ansible:playbook:find-missing:roles -- playbooks/qubes.yml`
+    cmds:
+      - |
+        TMP="$(mktemp)"
+        RESULTS="$(mktemp)"
+        while read ROLE; do
+          ROLE_TITLE="$(echo "$ROLE" | sed 's/^.\///')"
+          if ! grep "$ROLE_TITLE" '{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}main.yml{{end}}' > /dev/null; then
+            echo "$ROLE_TITLE" >> "$RESULTS"
+          fi
+        done< <(find ./roles -maxdepth 2 -mindepth 2)
+        if grep ".*" "$RESULTS"; then
+          .config/log info 'The roles missing from `{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}main.yml{{end}}` are:'
+          cat "$RESULTS"
+        else
+          .config/log info 'All of the roles are included in `{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}main.yml{{end}}`'
+        fi
 
   remotes:
     deps:
@@ -201,21 +337,40 @@ tasks:
         env:
           INSTALL_OPTIONS: --no-dev
       - :symlink:playbook
+    vars:
+      PLAYBOOK_MAIN:
+        sh: |
+          if [ -n "$PLAYBOOK_MAIN" ]; then
+            echo "$PLAYBOOK_MAIN"
+          else
+            echo "main.yml"
+          fi
     log:
       error: Error encounted while running `ansible-playbook -i inventories/{{.CLI_ARGS}} --ask-vault-pass main.yml`
       start: Running `ansible-playbook -i inventories/{{.CLI_ARGS}} --ask-vault-pass main.yml`
       success: Successfully ran `ansible-playbook -i inventories/{{.CLI_ARGS}} --ask-vault-pass main.yml`
     cmds:
-      - ansible-playbook -i inventories/{{.CLI_ARGS}} --ask-vault-pass main.yml
+      - |
+        PATH="$PATH:$HOME/.local/bin"
+        if [ -z "$ANSIBLE_VAULT_PASSWORD" ]; then
+          .config/log info 'The `ANSIBLE_VAULT_PASSWORD` environment variable is not set so you will be prompted for the password'
+          ansible-playbook -i {{.CLI_ARGS}} --ask-vault-pass "{{.PLAYBOOK_MAIN}}"
+        else
+          echo "$ANSIBLE_VAULT_PASSWORD" > "$HOME/.VAULT_PASSWORD"
+          export ANSIBLE_VAULT_PASSWORD_FILE="$HOME/.VAULT_PASSWORD"
+          .config/log info 'Bypassing Ansible Vault password prompt since the `ANSIBLE_VAULT_PASSWORD` environment variable is set'
+          ansible-playbook -i {{.CLI_ARGS}} "{{.PLAYBOOK_MAIN}}"
+        fi
 
   run:prompt:
+    summary: '{{.MARKDOWN}}'
     vars:
       MARKDOWN: |
         # Run the Playbook
 
         These set of prompts will run the `main.yml` playbook after you specify:
 
-        1. The "environment"
+        (1) The "environment"
 
         The environment is a collection of folders that should, at the very minimum,
         include "files", "group_vars", "host_vars", and "inventories". Each folder in
@@ -223,35 +378,71 @@ tasks:
         environments, you can seperate different sets of variables/files or even seperate
         your private variables out into a sub-module.
 
-        2. An inventory file
+        (2) An inventory file
 
         The Ansible inventory stored in the "inventories" folder. This will generally be
         a YML file with host connection information that also correlates the inventory with
         the proper host_vars and group_vars. It is assumed that your sudo username and
         password are encrypted inside the inventory (via "ansible-vault").
+      PLAYBOOK_DESCRIPTIONS: |
+        # Playbook Descriptions
+
+        Playbooks are where you store your main logic in Ansible. The `main.yml` file in the
+        root of the repository is a generic one-size-fits-all approach. You could theoretically
+        store all your logic in one playbook for multiple scenarios with conditional logic but
+        it might be easier to create seperate playbooks in some cases. The `main.yml` should work
+        in most scenarios and is a great starting point.
+
+        ## Alternate Playbook Descriptions
+
+        Alternate playbooks are stored in the `playbooks/` directory. They are described below.
+
+        *If you want their description to show up in this message, you will have to edit the appropriate
+        field in `package.json`.*
+
+    env:
+      MARKDOWN: '{{.MARKDOWN}}'
     cmds:
-      - task: environment
-      - task: :log:markdown
-        vars:
-          MARKDOWN: '{{.MARKDOWN}}'
+      - |
+        MD_TMP="$(mktemp)"
+        echo "$MARKDOWN" > "$MD_TMP"
+        .config/log md "$MD_TMP"
       - task: run:prompt:continue
 
   run:prompt:continue:
     interactive: true
     deps:
       - :install:software:jq
-    vars:
-      INVENTORY_OPTIONS:
-        sh: find ./inventories/ -mindepth 1 -maxdepth 1 | sed 's/\.\/inventories\///' | jq -R '[.]' | jq -s -c 'add'
-    prompt:
-      type: select
-      message: Which inventory would you like to use?
-      options: '{{.INVENTORY_OPTIONS}}'
-      answer:
-        cmds:
-          - task: run:cli
-            vars:
-              CLI_ARGS: '{{.ANSWER}}'
+    cmds:
+      - task: environment
+      - echo "\"inventories"$(find ./inventories/ -mindepth 1 -maxdepth 1 | sed 's/\.\/inventories\///' | jq -R '[.]' | jq -s -c -r 'add | join("\" \"inventories")')"\""
+      - |
+        INVENTORY_OPTIONS_LENGTH="$(find ./inventories/ -mindepth 1 -maxdepth 1 | sed 's/\.\/inventories\///' | jq -R '[.]' | jq -s -c -r 'add | length')"
+        if [[ "$INVENTORY_OPTIONS_LENGTH" == '0' ]]; then
+          .config/log error 'There are no inventory files present in the `inventories/` folder' && exit 1
+        else
+          INVENTORY_OPTIONS="$(echo "\""$(find ./inventories/ -mindepth 1 -maxdepth 1 | sed 's/\.\///' | jq -R '[.]' | jq -s -c -r 'add | join("\" \"")')"\"")"
+          .config/log prompt 'Which inventory would you like to use?'
+          CHOSEN_INVENTORY="$(.config/log choose $INVENTORY_OPTIONS)"
+          export PLAYBOOK_MAIN="main.yml"
+          if ! gum confirm "Would you like to use the main.yml playbook?"; then
+            PLAYBOOKS_OPTIONS="$(echo "\"playbooks"$(find ./playbooks/ -mindepth 1 -maxdepth 1 -name "*.yml" | sed 's/\.\/playbooks\///' | jq -R '[.]' | jq -s -c -r 'add | join("\" \"playbooks")')"\"")"
+            PLAYBOOK_DESCS_TMP="$(mktemp)" && echo "$PLAYBOOK_DESCRIPTIONS" > "$PLAYBOOK_DESCS_TMP"
+            TMP_LIST="$(mktemp)"
+            find ./playbooks/ -mindepth 1 -maxdepth 1 -name "*.yml" | sed 's/\.\/playbooks\///' | jq -R '[.]' | jq -s -c -r 'add' >> "$TMP_LIST"
+            echo "* **main.yml:** A generic playbook that attempts to install everything" >> "$PLAYBOOK_DESCS_TMP"
+            jq -c -r '.[]' "$TMP_LIST" | while read SLUG; do
+              PLAYBOOK_DESC="$(jq -r '.blueprint.fileDescriptions[$file]' package.json)"
+              if [ "$PLAYBOOK_DESC" != 'null' ]; then
+                echo "* **playbooks/${SLUG}.yml:** $PLAYBOOK_DESC" >> "$PLAYBOOK_DESCS_TMP"
+              fi
+            done
+            .config/log md "$PLAYBOOK_DESCS_TMP"
+            .config/log prompt 'Select the playbook you would like to provision with.'
+            export PLAYBOOK_MAIN="$(.config/log choose $PLAYBOOKS_OPTIONS)"
+          fi
+          task ansible:playbook:run:cli -- "$CHOSEN_INVENTORY"
+        fi
 
   subrepo:init:
     deps:
@@ -277,7 +468,48 @@ tasks:
       Usage:
       `task ansible:playbook:subrepo:init -- path/to/folder/with.git/folder`
     cmds:
+      - task: :git:commit:automated
       - |
         BASENAME="$(basename {{.CLI_ARGS}})"
         REMOTE="$(git remote get-url $BASENAME)"
         HUSKY=0 git subrepo init {{.CLI_ARGS}} -r "$REMOTE" -b master
+
+  types:
+    deps:
+      - :install:npm:quicktype
+    summary: |
+      # Generate Types from Vaulted Files
+
+      Automatically generate types from vaulted files.
+
+      **Example Usage:**
+      `task ansible:playbook:types -- ./environments/prod
+    vars:
+      TARGET_DIR: '{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}./environments/prod{{end}}'
+    cmds:
+      - task: vault:decrypt
+        vars:
+          TARGET_DIR: '{{.TARGET_DIR}}'
+      - |
+        qtype() {
+          local FILE_NO_EXT="$(echo "$1" | sed 's/.yml$//')"
+          yq e -o=json '.' $1 | quicktype -l schema -o ${FILE_NO_EXT}.schema.json
+        }
+        while read FILE; do
+          qtype "$FILE"
+        done < <(find {{.TARGET_DIR}} -type f -name "*vault.yml")
+      - task: vault:encrypt
+        vars:
+          TARGET_DIR: '{{.TARGET_DIR}}'
+
+  vault:decrypt:
+    vars:
+      TARGET_DIR: '{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}./environments/prod{{end}}'
+    cmds:
+      - find {{.TARGET_DIR}} -type f -name "*vault.yml" -printf "%h/\"%f\" " | xargs ansible-vault decrypt
+
+  vault:encrypt:
+    vars:
+      TARGET_DIR: '{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}./environments/prod{{end}}'
+    cmds:
+      - find {{.TARGET_DIR}} -type f -name "*vault.yml" -printf "%h/\"%f\" " | xargs ansible-vault encrypt
diff --git a/roles/misc/nexus3-oss/.config/taskfiles/ansible/Taskfile.yml b/roles/misc/nexus3-oss/.config/taskfiles/ansible/Taskfile.yml
--- a/roles/misc/nexus3-oss/.config/taskfiles/ansible/Taskfile.yml
+++ b/roles/misc/nexus3-oss/.config/taskfiles/ansible/Taskfile.yml
@@ -6,9 +6,10 @@ vars:
   MAIN_TASKS_PATH: tasks/main.yml
   META_PATH: meta/main.yml
   MOLECULE_RESULTS_PATH: molecule/.results
+  PRE_SHARED_VAULT_KEY: YTtEnhPWtftHFcP3HneVmz6vX2qMqAwobTDAbvDwrdyunAaDCQ
   REQUIREMENTS_PATH: requirements.yml
   ROLE_NAME: '{{.GALAXY_NAMESPACE}}.{{.GALAXY_ROLE_NAME}}'
-  SAMPLE_PROJECT: https://github.com/ProfessorManhattan/ansible-snapd
+  SAMPLE_PROJECT: https://github.com/megabyte-labs/ansible-snapd
   VARIABLES_PATH: .variables.json
 
 tasks:
@@ -83,25 +84,19 @@ tasks:
       - '[ -z "$ANSIBLE_GALAXY_TOKEN" ]'
 
   galaxy:requirements:
-    run: once
-    cmds:
-      - task: galaxy:requirements:install
-    sources:
-      - requirements.yml
-    preconditions:
-      - sh: test -f requirements.yml
-        msg: The requirements.yml file is missing! It should be present even if it is empty (which should almost never be the case).
-
-  galaxy:requirements:install:
     log:
       error: Error encountered while installing the Ansible Galaxy requirements specified in `requirements.yml`
       start: Installing the Ansible Galaxy requirements specified in `requirements.yml`
       success: Installed the Ansible Galaxy requirements specified in `requirements.yml`
     cmds:
+      - |
+        if [ -f ~/.netrc ]; then
+          chmod 600 ~/.netrc
+        fi
       - cmd: '{{.PYTHON_HANDLE}} ansible-galaxy install -r requirements.yml --ignore-errors'
         ignore_error: true
-    status:
-      - '[[ "${container:=}" == "docker" ]]'
+    sources:
+      - requirements.yml
 
   init:
     cmds:
@@ -144,7 +139,7 @@ tasks:
         fi
         jq -r --argjson result "$MERGED_TAGS" '.keywords = $result' package.json > "$TMP"
         mv "$TMP" package.json
-        {{.NPX_HANDLE}}prettier --write package.json > /dev/null
+        prettier --write package.json > /dev/null
         mkdir -p .cache/megabytelabs
         jq -n --argjson result "$RESULT" --argjson gi "$GALAXY_INFO" '$gi | .galaxy_info.galaxy_tags = $result' > .cache/megabytelabs/galaxy-meta.json
         yq eval -P .cache/megabytelabs/galaxy-meta.json > meta/main.yml
@@ -156,22 +151,19 @@ tasks:
           CLI_ARGS: meta/main.yml
 
   mod-ansible-autodoc:
+    todo: Add ansible-autodoc-fork to the includes of the package
     cmds:
+      - |
+        if [ -n "$CI" ]; then
+          pip3 install ansible-autodoc-fork
+        fi
       - task: mod-ansible-autodoc:generate
       - task: mod-ansible-autodoc:variables
 
-  mod-ansible-autodoc:ansible-autodoc-fork:
-    cmds:
-      - task: :install:software:pipx
-      - task: :install:python:pipx
-        vars:
-          PACKAGE: ansible-autodoc-fork
-
   mod-ansible-autodoc:generate:
     deps:
-      - :install:python:requirements
+      - :install:pipx:mod-ansible-autodoc
       - :install:software:jq
-      - mod-ansible-autodoc:ansible-autodoc-fork
     env:
       ACTIONS_DESCRIPTION:
         sh: jq -r '.autodoc_actions_description' '{{.VARIABLES_PATH}}'
@@ -216,6 +208,8 @@ tasks:
         mv "$TMP" '{{.VARIABLES_PATH}}'
 
   prepare:
+    deps:
+      - :ci:commit:config
     log:
       error: Failed to ensure GitLab and GitHub are in sync
       start: Preparing for Ansible Galaxy upload
@@ -231,27 +225,251 @@ tasks:
 
   quickstart:
     deps:
-      - :ansible:symlink:{{.REPOSITORY_SUBTYPE}}
+      - :install:software:jq
+      - :symlink:{{.REPOSITORY_SUBTYPE}}
       - task: :install:python:requirements
         vars:
           INSTALL_OPTIONS: --no-dev
+    cmds:
+      - task: quickstart:environment
+      - task: quickstart:map
+      - task: quickstart:demo
+
+  quickstart:cli:
+    deps:
+      - :install:software:openssl
+    summary: |
+      # Ansible Quickstart CLI
+
+      Use this task if you already know the inventory file you would like to run the
+      `main.yml` playbook on. The unique feature is that this task will first run
+      `playbooks/init.yml` (and skip any task tagged with `skip_on_init`), reboot,
+      and then run the normal `main.yml`. This allows you to provision a single computer
+      that serves both as the client and host of Ansible (since some software requires
+      reboots).
+
+      {{.QUICKSTART_VAULT_SECURITY}}
     vars:
-      INSTALLING:
-        sh: if test -f install_in_progress; then echo 'true'; else echo 'false'; fi
+      INVENTORY: '{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}inventories/local.yml{{end}}'
+      QUICKSTART_VAULT_SECURITY: |
+        ## Ansible Vault Password Security
+
+        To achieve automation wherever possible, we save your Ansible Vault password
+        on disk during the installation process (i.e. to preserve the information
+        inbetween reboots).
+
+        To make it more secure, we employ the following measures:
+        1. The password is forcibly removed anytime the ansible-playbook command fails
+        2. It is passed in via the `ANSIBLE_VAULT_PASSWORD` variable to minimize the possibility
+        of the password displaying in the terminal or getting added to the command history.
+        3. It is stored in `~/.VAULT_PASSWORD` so you can easily spot it if something
+        goes wrong.
+    env:
+      ANSIBLE_VAULT_PASSWORD_FILE: ~/.VAULT_PASSWORD
+      QUICKSTART_PLAYBOOK_MATCH: |
+        # Playbook Matching Inventory File Name
+
+        A playbook with the same file name as the selected inventory was found in the
+        `playbooks/` directory. When the file names match up, this "quick start" script
+        will use the matching playbook file instead of the `main.yml` playbook found in
+        the root of the repository.
+      QUICKSTART_VAULT_SECURITY: '{{.QUICKSTART_VAULT_SECURITY}}'
     log:
       error: Error occurred while running the Ansible play
       start: Running the Ansible play locally
       success: Successfully ran the Ansible play locally
     cmds:
-      - cp test/{{OS}}/inventory inventory
-      - if [ ! -f ansible.cfg.bak ]; then cp ansible.cfg ansible.cfg.bak; fi
-      - cp test/{{OS}}/ansible.cfg ansible.cfg
-      - touch install_in_progress
+      - cmd: |
+          if [ ! -f "$ANSIBLE_VAULT_PASSWORD_FILE" ]; then
+            .config/log info 'Adding `~/ANSIBLE_PLAYBOOK_CONTINUE.sh` to run on reboot'
+            echo "#!/usr/env/bin bash" > ~/ANSIBLE_PLAYBOOK_CONTINUE.sh
+            echo "" > ~/ANSIBLE_PLAYBOOK_CONTINUE.sh
+            echo "cd $PWD" >> ~/ANSIBLE_PLAYBOOK_CONTINUE.sh
+            echo 'task ansible:quickstart:cli -- {{.INVENTORY}}' >> ~/ANSIBLE_PLAYBOOK_CONTINUE.sh
+            if [ -z "$ANSIBLE_VAULT_PASSWORD" ]; then
+              MD_TMP="$(mktemp)"
+              echo "$QUICKSTART_VAULT_SECURITY" > "$MD_TMP"
+              .config/log md "$MD_TMP"
+              .config/log info 'Read about security measures above.'
+              .config/log prompt 'What is your Ansible Vault password?'
+              export ANSIBLE_VAULT_PASSWORD="$(.config/log password 'Enter Vault password (leave empty if there is not a password yet)..')"
+            fi
+          fi
+          .config/log info 'Writing the `ANSIBLE_VAULT_PASSWORD` to temporary file in user home directory'
+          echo "$ANSIBLE_VAULT_PASSWORD" > ~/.VAULT_PASSWORD
+          INVENTORY="{{.INVENTORY}}"
+          INVENTORY_SLUG="$(echo "$INVENTORY" | sed 's/inventories\/\(.*\).yml/\1/')"
+          if [[ '{{.INVENTORY}}' == 'inventories/quickstart.yml' ]]; then
+            if [ -f '/etc/qubes-rpc' ] && [[ "$(whoami)" == 'user' ]]; then
+              .config/log info 'Assuming `ANSIBLE_USER` name to be `user` since this is Qubes'
+              export ANSIBLE_USER="user"
+            elif [ -z "$ANSIBLE_USER" ]; then
+              WHOAMI="$(whoami)"
+              .config/log prompt 'In the next step, select a user with `sudo` privileges'
+              if ! .config/log confirm 'Run playbook with `'"${WHOAMI}"'`?'; then
+                export ANSIBLE_USER="$(.config/log input 'Enter the username of the admin account you wish to use..')"
+              else
+                export ANSIBLE_USER="$WHOAMI"
+              fi
+            else
+              .config/log info '`ANSIBLE_USER` is set to `'"$ANSIBLE_USER"'`'
+            fi
+            if [ -z "$ANSIBLE_PASSWORD" ]; then
+              if sudo -n echo &> /dev/null; then
+                .config/log info 'Assuming passwordless sudo since `sudo -n echo` was truthy'
+                .config/log info 'Bypassing `ANSIBLE_PASSWORD` prompt'
+              else
+                .config/log prompt 'Enter the `sudo` password for your selected user (`'"$ANSIBLE_USER"'`)'
+                export ANSIBLE_PASSWORD="$(.config/log password 'Enter password (or just press enter if there is none)..')"
+              fi
+            else
+              .config/log info '`ANSIBLE_PASSWORD` is present as an environment variable.. bypassing password prompt'
+            fi
+            if [ -z "$MOLECULE_GROUP" ]; then
+              if [ -f '/etc/qubes-rpc' ]; then
+                .config/log info 'Machine is a Qubes dom0 environment'
+                export MOLECULE_GROUP="qubes"
+              else
+                .config/log info 'Assuming machine to be macOS/Linux'
+                export MOLECULE_GROUP="nix"
+              fi
+            fi
+          fi
+          if [ -f "playbooks/${INVENTORY_SLUG}.yml" ]; then
+            PLAY_TMP="$(mktemp)" && echo "$QUICKSTART_PLAYBOOK_MATCH" > "$PLAY_TMP" && .config/log md "$PLAY_TMP"
+            {{.PYTHON_HANDLE}}ansible-playbook -i {{.INVENTORY}} "playbooks/${INVENTORY_SLUG}.yml"
+          else
+            .config/log info 'Using the `main.yml` playbook because there is no playbook located in `'"playbooks/${INVENTORY_SLUG}.yml"'`'
+            {{.PYTHON_HANDLE}}ansible-playbook -i {{.INVENTORY}} main.yml
+          fi
+        ignore_error: true
+      - sleep 5
+      - .config/log info 'Ensuring the temporary vault password file is forcibly removed'
+      - rm -f ~/.VAULT_PASSWORD
+      - rm -f ~/ANSIBLE_PLAYBOOK_CONTINUE.sh
+
+  quickstart:demo:
+    cmds:
+      - task: quickstart:cli
+    status:
+      - '[ -f files/inventory-map.json ]'
+
+  quickstart:environment:
+    cmds:
+      - task: :ansible:playbook:environment:cli
+        vars:
+          CLI_ARGS:
+            sh: echo "$ENV"
+    status:
+      - '[ -z "$ENV" ]'
+
+  quickstart:map:
+    deps:
+      - :install:pipx:getmac
+      - :install:software:gum
+      - :install:software:jq
+    summary: |
+      # Quickstart Mapping
+
+      This task is a helper task that attempts to automatically select the appropriate
+      Ansible inventory based on the MAC address. If the mapping entry is not already
+      saved, this task will guide the user through a series of prompts.
+
+      {{.MAC_ADDRESS_EXPLANATION}}
+    vars:
+      INVENTORY_OPTIONS:
+        sh: echo "\""$(find ./inventories/ -mindepth 1 -maxdepth 1 | sed 's/\.\/inventories\//inventories\//' | jq -R '[.]' | jq -s -c -r 'add | join("\" \"")')"\""
+      INVENTORY_OPTIONS_LENGTH:
+        sh: find ./inventories/ -mindepth 1 -maxdepth 1 | sed 's/\.\/inventories\///' | jq -R '[.]' | jq -s -c -r 'add | length'
+      MAC_ADDRESS_EXPLANATION: |
+        ## Mapping MAC Addresses to Inventory Files
+
+        In order to achieve a completely automated flow, we have the ability
+        to define a map of MAC addresses and inventory files in the `files/`
+        folder.
+
+        You can get your MAC address by using the `getmac` program that this
+        task installs or you can run the following on Linux:
+
+        ```
+        cat /sys/class/net/$(ip route show default | awk '/default/ {print $5}')/address
+        ```
+
+        On Windows, if you are provisioning with Docker (the default "Quick Start" method)
+        and if you make sure you are running it on either a clean system or have no other
+        Docker containers running, then the MAC address will be:
+
+        ```
+        02:42:ac:11:00:02
+        ```
+
+        If you wanted to run the Quick Start method on Windows, you could create a file in
+        `files/inventory-map.json` that looks something like this:
+
+        ```
+        {
+          "02:42:ac:11:00:02": "inventories/workstation.yml"
+        }
+        ```
+
+        This configuration would instruct the script to automatically use the `inventories/workstation.yml`
+        inventory. If your MAC address is missing, the script will open an interactive prompt and include
+        the ability to save your MAC address to the file for later use.
+    env:
+      INVENTORY_EXPLANATION: |
+        # Which Inventory Should I Use?
+
+        A special / great starting point is the `quickstart.yml` inventory which allows you to pass your username
+        and password through a prompt. It is intended to be used to provision one machine at a time from that machine.
+        It is also intended to be used with the **Quick Start** links at the top of the README.md. It can be used to
+        provision any of our supported operating systems.
+
+        ## TLDR: Choose `quickstart.yml`
+      MAC_ADDRESS_EXPLANATION: '{{.MAC_ADDRESS_EXPLANATION}}'
+    cmds:
       - |
-        .config/log info 'Prompting for sudo password which is required to run the playbook'
-        {{.PYTHON_HANDLE}}ansible-playbook --ask-sudo-pass{{if eq .INSTALLING 'false'}} --skip-tags "skip_on_init" playbooks/init.yml{{else}} main.yml{{end}}
-      - if [ -f ansible.cfg.bak ]; then mv ansible.cfg.bak ansible.cfg; fi
-      - if [ -f inventory ]; then rm inventory; fi
+        PATH="$PATH:$HOME/.local/bin"
+        # MAC_ADDRESS="$(cat /sys/class/net/$(ip route show default | awk '/default/ {print $5}')/address)" # Does not work on macOS
+        MAC_ADDRESS="$(getmac)"
+        TARGET_INV="$(jq --arg macAddress "$MAC_ADDRESS" -r '.[$macAddress]' files/inventory-map.json)"
+        if [[ "$TARGET_INV" == '' ]]; then
+          .config/log warn 'Initializing `files/inventory-map.json` since it appears to be an empty file'
+          echo '{}' > files/inventory-map.json
+        fi
+        if [ "$TARGET_INV" != 'null' ] && [ "$TARGET_INV" != '' ]; then
+          .config/log info "Provisioning with "'`'"$TARGET_INV"'`'
+          task ansible:quickstart:cli -- "$TARGET_INV"
+        else
+          MD_TMP="$(mktemp)"
+          echo "$MAC_ADDRESS_EXPLANATION" > "$MD_TMP"
+          .config/log md "$MD_TMP"
+          .config/log warn "MAC address missing from inventory-map.json ($MAC_ADDRESS). Details printed above."
+          if [ '{{.INVENTORY_OPTIONS_LENGTH}}' != '0' ]; then
+            .config/log prompt 'Given the information above, would you like to save your MAC address to the `files/inventory-map.json` file?'
+            if .config/log confirm 'Save MAC address?'; then
+              INV_TMP="$(mktemp)" && echo "$INVENTORY_EXPLANATION" > "$INV_TMP" && .config/log md "$INV_TMP"
+              .config/log prompt 'Which inventory file would you like the associate the MAC address with?'
+              INVENTORY_FILE="$(.config/log choose {{.INVENTORY_OPTIONS}})"
+              TMP="$(mktemp)"
+              .config/log info 'Generating new `files/inventory-map.json` file'
+              jq --arg inventory "$INVENTORY_FILE" --arg macaddr "$MAC_ADDRESS" '.[$macaddr] = $inventory' files/inventory-map.json > "$TMP"
+              mv "$TMP" files/inventory-map.json
+              .config/log success "Successfully associated the selected inventory with this machine's MAC address (remember to git add / commit)"
+              task ansible:quickstart:cli -- "$INVENTORY_FILE"
+            else
+              INV_TMP="$(mktemp)" && echo "$INVENTORY_EXPLANATION" > "$INV_TMP" && .config/log md "$INV_TMP"
+              .config/log prompt 'Which inventory file would you like to use?'
+              INVENTORY_FILE="$(.config/log choose {{.INVENTORY_OPTIONS}})"
+              task ansible:quickstart:cli -- "$INVENTORY_FILE"
+            fi
+          else
+            .config/log error 'There are no inventories defined in the `inventories/` folder.'
+            .config/log info 'Try running `task environment` to link to sample environments'
+            exit 1
+          fi
+        fi
+    status:
+      - '[ ! -f files/inventory-map.json ]'
 
   sync:requirements:
     deps:
diff --git a/roles/misc/nexus3-oss/.config/taskfiles/ci/Taskfile.yml b/roles/misc/nexus3-oss/.config/taskfiles/ci/Taskfile.yml
--- a/roles/misc/nexus3-oss/.config/taskfiles/ci/Taskfile.yml
+++ b/roles/misc/nexus3-oss/.config/taskfiles/ci/Taskfile.yml
@@ -24,20 +24,25 @@ tasks:
       - pnpm config set store-dir .pnpm-store
 
   checkout:
+    deps:
+      - :install:software:git
     log:
       error: Failed to pull latest changes
       start: Pulling latest changes
       success: Successfully pulled latest changes
     cmds:
-      - git fetch --all --tags -f
+      - cmd: git pull
+        ignore_error: true
       - |
-        if [[ "$CI_COMMIT_REF_NAME" == 'synchronize' ]]; then
-          git checkout -q master
-          git pull -q origin master
+        if [ "$CI_COMMIT_REF_NAME" == 'synchronize' ]; then
+          git checkout master
+          git pull origin master
         else
-          git checkout -q "$CI_COMMIT_REF_NAME"
-          git pull -q origin "$CI_COMMIT_REF_NAME"
+          git checkout "$CI_COMMIT_REF_NAME"
+          git pull origin "$CI_COMMIT_REF_NAME"
         fi
+    status:
+      - '[ -n "$NO_GIT_CREDS" ]'
 
   codeclimate:
     deps:
@@ -53,7 +58,8 @@ tasks:
         else
           curl -sSL https://gitlab.com/megabyte-labs/common/shared/-/raw/master/.config/codeclimate.yml > .codeclimate.yml
         fi
-      - docker pull codeclimate/codeclimate
+      - docker pull megabytelabs/codeclimate-internet
+      - docker tag megabytelabs/codeclimate-internet codeclimate/codeclimate
       - task: :lint:codeclimate:load:custom-engines
       - task: codeclimate:gitlab
 
@@ -67,25 +73,37 @@ tasks:
   commit:
     deps:
       - :install:software:git
+    vars:
+      CURR_BRANCH:
+        sh: git rev-parse --abbrev-ref HEAD
     log:
-      error: Encountered error while pushing changes to master
-      start: Bypassing git hooks and pushing changes to master (if there are any changes)
+      error: Encountered error while pushing changes to {{.CURR_BRANCH}}
+      start: Bypassing git hooks and pushing changes to {{.CURR_BRANCH}} (if there are any changes)
     cmds:
       - task: commit:config
       - task: lockfiles:clean
+      - task --list > /dev/null || (echo "ERROR Invalid Taskfiles!" && exit 1)
       - git add --all
       - git diff --cached "*"
       - |
         if [[ $(git status --porcelain) ]]; then
-          git commit -m "⤵️ automation(synchronize) Applying changes from upstream repository."
-          git push -q -o ci.skip origin master
+          git commit -m "☁️ chore(automation): Applying changes from upstream repository."
+          git push -q -o ci.skip origin {{.CURR_BRANCH}} || FAILED_PUSH=$?
+          if [ -n "$FAILED_PUSH" ]; then
+            git pull -X theirs origin {{.CURR_BRANCH}}
+            task --list &> /dev/null || (echo "ERROR: Invalid Taskfiles!" && exit 1)
+            git add --all
+            git commit -m "☁️ chore(automation): Merging changes from upstream repository with -X theirs."
+            git push --force -q -o ci.skip origin {{.CURR_BRANCH}}
+          fi
         fi
     status:
-      - '[ -z "$CI" ]'
+      - '[ -z "$CI" ] || [ -n "$NO_GIT_CREDS" ]'
 
   commit:config:
     deps:
       - :install:software:git
+    run: once
     log:
       error: Error configuring git
       start: Configuring git to use CI-friendly parameters
@@ -94,15 +112,8 @@ tasks:
       - git remote set-url origin "https://root:$GROUP_ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
       - git config user.email "$GITLAB_CI_EMAIL"
       - git config user.name "$GITLAB_CI_NAME"
-    preconditions:
-      - sh: '[[ ! -z "$GROUP_ACCESS_TOKEN" ]]'
-        msg: The `GROUP_ACCESS_TOKEN` GitLab CI variable must be set to an API key with priviledges to read/write to repositories.
-      - sh: '[[ ! -z "$GITLAB_CI_EMAIL" ]]'
-        msg: 'The `GITLAB_CI_EMAIL` GitLab CI variable must be set to the e-mail address you would like associated with
-          automated commits (e.g. "help@mydomain.com").'
-      - sh: '[[ ! -z "$GITLAB_CI_NAME" ]]'
-        msg: 'The `GITLAB_CI_NAME` GitLab CI variable must be set to the name you would like associated with automated commits
-          (e.g. "CI Automation").'
+    status:
+      - '[ -z "$GROUP_ACCESS_TOKEN" ] || [ -z "$GITLAB_CI_EMAIL" ] || [ -z "$GITLAB_CI_NAME" ] || [ -z "$GITLAB_CI" ]'
 
   lockfiles:
     cmds:
@@ -126,6 +137,10 @@ tasks:
           rm -f yarn.lock
         fi
 
+  mirror:github:
+    deps:
+      - :donothing
+
   submodules:
     deps:
       - :install:software:git
@@ -136,26 +151,40 @@ tasks:
     cmds:
       - >
         git submodule foreach 'git config user.email "$GITLAB_CI_EMAIL"; git config user.name "$GITLAB_CI_NAME";
-        git checkout -q master; git pull -q origin master --ff-only'
+        DEFAULT_BRANCH="$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')";
+        git checkout -q "$DEFAULT_BRANCH"; git pull -q origin "$DEFAULT_BRANCH" --ff-only'
     status:
-      - '[ -z "$CI" ]'
+      - '[ -z "$CI" ] || [ -n "$NO_GIT_CREDS" ]'
 
   synchronize:
+    deps:
+      - commit:config
+    run: once
     log:
       error: Failed to update the `synchronize` branch
       start: Synchronizing the `synchronize` branch with the `master` branch
       success: Successfully updated the `synchronize` branch
     cmds:
+      - git fetch origin
       - git checkout -b synchronize || git checkout synchronize
       - git reset --hard HEAD
       - git pull -q origin master
-      - git push -q -o ci.skip origin synchronize --force
       - |
-        if [ '{{.REPOSITORY_TYPE}}' == 'deprecated_common' ] && [ '{{.REPOSITORY_SUBTYPE}}' == 'shared' ]; then
-          .config/log info 'Bypassing the `master` branch pipeline trigger because the repository is not of the right type'
-        else
-          .config/log info 'Triggering the `master` branch pipeline'
-          curl -s --request POST --form "token=${CI_JOB_TOKEN}" --form ref=master --form "variables[PIPELINE_SOURCE]=$PIPELINE_SOURCE" \
-            "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/trigger/pipeline"
+        git push --force -q -o ci.skip origin synchronize || FAILED_SYNC=$?
+        if [ -n "$FAILED_SYNC" ]; then
+          task git:gitlab:protected:off -- "synchronize"
+          git push --force -q -o ci.skip origin synchronize
         fi
+      - task: synchronize:gitlab
       - git checkout master
+      - task: :ci:github:synchronize
+    status:
+      - '[ -n "$NO_GIT_CREDS" ] || ([ "$FULLY_AUTOMATED_TASKS" != "true" ] && [ -z "$CI" ])'
+
+  synchronize:gitlab:
+    run: once
+    cmds:
+      - curl -s --request POST --form "token=${CI_JOB_TOKEN}" --form ref=master --form "variables[PIPELINE_SOURCE]=$PIPELINE_SOURCE"
+        "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/trigger/pipeline"
+    status:
+      - '[ -z "$GITLAB_CI" ] || [ -n "$NO_GITLAB_SYNCHRONIZE" ]'
diff --git a/roles/misc/nexus3-oss/.config/taskfiles/fix/Taskfile.yml b/roles/misc/nexus3-oss/.config/taskfiles/fix/Taskfile.yml
--- a/roles/misc/nexus3-oss/.config/taskfiles/fix/Taskfile.yml
+++ b/roles/misc/nexus3-oss/.config/taskfiles/fix/Taskfile.yml
@@ -23,7 +23,7 @@ tasks:
     deps:
       - :install:modules:local
       - :install:npm:eslint
-      - :install:software:expect
+      - :install:software:unbuffer
     desc: Fix ESLint errors automatically
     summary: |
       # Fix Errors with ESLint Automatically
@@ -37,28 +37,29 @@ tasks:
 
       **Example fixing all files in a project:**
       `task fix:js`
+    vars:
+      ESLINT_LOG:
+        sh: mktemp
     log:
       error: ESLint found some issues that need to be fixed manually
       start: Auto-fixing with ESLint
       success: ESLint fixing appears to have corrected all the issues {{if .CLI_ARGS}}in `{{.CLI_ARGS}}`{{else}}in the project{{end}}
     cmds:
-      - 'unbuffer {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache --cache-location .cache/eslintcache
-        --fix {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} | tee eslint.log'
+      - 'unbuffer eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache --cache-location .cache/eslintcache
+        --fix {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} | tee {{.ESLINT_LOG}}'
       - |
         if [ '{{.ESLINT_FIX_RECURSIVE}}' == 'true' ]; then
           COUNT=0
           while [ $COUNT -le 5 ]; do
             COUNT=$((COUNT + 1))
-            if grep 'potentially fixable with the `--fix` option' < eslint.log > /dev/null; then
+            if grep 'potentially fixable with the `--fix` option' < {{.ESLINT_LOG}} > /dev/null; then
               COUNT="$COUNT"
-              unbuffer {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache --cache-location .cache/eslintcache \
-              --fix {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} | tee eslint.log
-            else
-              echo '' > eslint.log
+              unbuffer eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache --cache-location .cache/eslintcache \
+              --fix {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} | tee {{.ESLINT_LOG}}
             fi
           done
         fi
-      - rm eslint.log
+      - rm {{.ESLINT_LOG}}
 
   eslint:staged:
     deps:
@@ -73,7 +74,7 @@ tasks:
       success: Successfully auto-fixed modified files with ESLint
     cmds:
       - >
-        {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache
+        eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache
         --cache-location .cache/eslintcache --fix {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   go:
@@ -95,7 +96,7 @@ tasks:
       start: Auto-fixing Go files..
       success: Successfully auto-fixed Go files
     cmds:
-      - golangci-lint run -c .config/golangci.yml --fix{{if .CLI_ARGS}}{{.CLI_ARGS}}{{end}}
+      - golangci-lint run -c .config/golangci.yml --fix{{if .CLI_ARGS}} {{.CLI_ARGS}}{{end}}
 
   js:
     cmds:
@@ -122,8 +123,8 @@ tasks:
       start: Linting JSON with ESLint
       success: ESLint has fixed all of the JSON issues {{if .CLI_ARGS}}in `{{.CLI_ARGS}}`{{else}}in the project{{end}}
     cmds:
-      - '{{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --cache --cache-location .cache/eslintcache --fix
-        --format pretty --ext .json {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+      - eslint -c package.json --no-eslintrc --cache --cache-location .cache/eslintcache --fix
+        --format pretty --ext .json {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   markdown:
     deps:
@@ -159,7 +160,7 @@ tasks:
 
   misc:
     deps:
-      - :install:python:requirements
+      - :install:pipx:pre-commit-hooks
     summary: |
       # Miscellaneous fixes
 
@@ -180,9 +181,10 @@ tasks:
       success: Finished performing miscellaneous fixes{{if .CLI_ARGS}} on `{{.CLI_ARGS}}`{{end}}
     cmds:
       - |
+        PATH="$PATH:$HOME/.local/bin"
         function misc() {
-          {{.PYTHON_HANDLE}}fix-byte-order-marker "$1"
-          {{.PYTHON_HANDLE}}mixed-line-ending --fix=lf "$1"
+          fix-byte-order-marker "$1"
+          mixed-line-ending --fix=lf "$1"
         }
         {{if .CLI_ARGS}}
           misc '{{.CLI_ARGS}}'
@@ -275,16 +277,20 @@ tasks:
       start: Running Prettier on {{if .CLI_ARGS}}`{{.CLI_ARGS}}`{{else}}project{{end}}
     cmds:
       - cmd: |
-          {{.NPX_HANDLE}}prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} || EXIT_CODE=$?
+          prettier --plugin node_modules/prettier-plugin-toml-fixed --ignore-path {{.PRETTIERIGNORE_CONFIG}} \
+          --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} || EXIT_CODE=$?
           if [ -n "$EXIT_CODE" ]; then
-            .config/log warn 'Failed to run `{{.NPX_HANDLE}}prettier` - falling back to `prettier`'
-            prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
+            .config/log warn 'Failed to run `prettier` - falling back to `prettier`'
+            prettier --plugin node_modules/prettier-plugin-toml-fixed --ignore-path {{.PRETTIERIGNORE_CONFIG}} \
+            --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
           fi
         ignore_error: true
 
   python:
     deps:
-      - :install:python:requirements
+      - :install:pipx:add-trailing-comma
+      - :install:pipx:isort
+      - :install:pipx:pyformat
     desc: Automatically format Python files using Black
     hide: '{{ne .REPOSITORY_TYPE "python"}}'
     summary: |
@@ -307,11 +313,16 @@ tasks:
       success: Fixed {{if .CLI_ARGS}}`{{.CLI_ARGS}}`{{else}}project{{end}} with `black`
     cmds:
       - |
+        PATH="$PATH:$HOME/.local/bin"
         {{if .CLI_ARGS}}
-          {{.PYTHON_HANDLE}}black {{.CLI_ARGS}}
+          pyformat -i {{.CLI_ARGS}}
+          isort --overwrite-in-place {{.CLI_ARGS}}
+          add-trailing-comma --exit-zero-even-if-changed {{.CLI_ARGS}}
         {{else}}
           while read PATHH; do
-            {{.PYTHON_HANDLE}}black "$PATHH"
+            pyformat -i "$PATHH"
+            isort --overwrite-in-place "$PATHH"
+            add-trailing-comma --exit-zero-even-if-changed "$PATHH"
           done < <(find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.py' \))
         {{end}}
 
@@ -353,10 +364,10 @@ tasks:
       - |
         .config/log warn 'This is an experimental fix method - please manually inspect and test the scripts'
         {{if .CLI_ARGS}}
-          {{.NPX_HANDLE}}shellcheck -e {{.SHELLCHECK_EXCLUDE}} -f diff {{.CLI_ARGS}} | git apply
+          shellcheck -e {{.SHELLCHECK_EXCLUDE}} -f diff {{.CLI_ARGS}} | git apply
         {{else}}
           find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.sh' -o -name '*.sh.j2' \) \
-            -print0 | xargs -0 {{.NPX_HANDLE}}shellcheck -e {{.SHELLCHECK_EXCLUDE}} -f diff | git apply
+            -print0 | xargs -0 shellcheck -e {{.SHELLCHECK_EXCLUDE}} -f diff | git apply
         {{end}}
 
   spelling:markdown:
@@ -378,7 +389,7 @@ tasks:
 
   toml:
     deps:
-      - :install:python:requirements
+      - :install:pipx:toml-sort
     desc: Format `.toml` files by alphabetizing and flattening
     summary: |
       # Automatically format `.toml` files
@@ -397,11 +408,14 @@ tasks:
       success: Successfully ran the `toml-sort` auto-fixer
     cmds:
       - |
+        PATH="$PATH:$HOME/.local/bin"
         {{if .CLI_ARGS}}
-          {{.PYTHON_HANDLE}}toml-sort -i --all {{.CLI_ARGS}}
+        if [ -f '{{.CLI_ARGS}}' ]; then
+          toml-sort -i --all {{.CLI_ARGS}}
+        fi
         {{else}}
           while read PATHH; do
-            {{.PYTHON_HANDLE}}toml-sort -i --all "$PATHH"
+            toml-sort -i --all "$PATHH"
           done < <(find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.toml' \))
         {{end}}
 
@@ -424,8 +438,8 @@ tasks:
       start: Attempting to auto-fix any XML files with ESLint
       success: Any XML files present in the project were successfully fixed/validated by ESLint
     cmds:
-      - '{{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --cache --cache-location .cache/eslintcache --fix
-        --format pretty --ext .xml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+      - eslint -c package.json --no-eslintrc --cache --cache-location .cache/eslintcache --fix
+        --format pretty --ext .xml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   yaml:
     desc: Auto-format and sort YML files
@@ -509,5 +523,5 @@ tasks:
       start: Ensuring YML file(s) are in order specified in configuration
       success: Successfully ensured YML file order
     cmds:
-      - '{{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format pretty --fix --cache
-        --cache-location .cache/eslintcache --ext yml,yaml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+      - eslint -c package.json --no-eslintrc --format pretty --fix --cache
+        --cache-location .cache/eslintcache --ext yml,yaml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
diff --git a/roles/misc/nexus3-oss/.config/taskfiles/git/Taskfile-github.yml b/roles/misc/nexus3-oss/.config/taskfiles/git/Taskfile-github.yml
--- a/roles/misc/nexus3-oss/.config/taskfiles/git/Taskfile-github.yml
+++ b/roles/misc/nexus3-oss/.config/taskfiles/git/Taskfile-github.yml
@@ -4,6 +4,7 @@ version: '3'
 tasks:
   create:
     deps:
+      - :ci:commit:config
       - :install:software:gh
       - :install:software:jq
       - :git:remotes
@@ -22,14 +23,16 @@ tasks:
       start: Checking for presence of GitHub repository and creating one if it does not exist
       success: Ensure GitHub repository is present
     cmds:
-      - cmd: gh repo create "{{.GITHUB_SLUG}}" --enable-wiki={{.GITHUB_WIKI}} -y --description "{{.EMOJI_START}}{{.DESCRIPTION}}{{.EMOJI_END}}"
+      - cmd: |
+          gh repo create "{{.GITHUB_ORG}}/{{.GITHUB_SLUG}}" --enable-wiki={{.GITHUB_WIKI}} -y --description "{{.EMOJI_START}}{{.DESCRIPTION}}{{.EMOJI_END}}" \
           --homepage "{{.HOMEPAGE}}" {{.PROJECT_TYPE}} > /dev/null
+          task --list > /dev/null || (echo "ERROR: Invalid Taskfiles!" && exit 1)
+          git add --all
+          git commit --quiet -m "✨ feat(birth): Birth" -n || true
+          git push github master
         ignore_error: true
-      - git add --all
-      - git commit --quiet -m "🎂 Birth" -n || true
-      - git push --quiet -u --no-progress github master
     status:
-      - '[ -z "$GITHUB_TOKEN" ] || ! test -e .git || gh repo view {{.GITHUB_ORG}}/{{.GITHUB_SLUG}} > /dev/null'
+      - '[ -z "$GITHUB_TOKEN" ] || (test -d .git && gh repo view "{{.GITHUB_ORG}}/{{.GITHUB_SLUG}}" > /dev/null)'
     preconditions:
       - sh: '[ "{{.DESCRIPTION}}" != "null" ]'
         msg: The `.description` in `package.json` must be set.
@@ -57,7 +60,38 @@ tasks:
     status:
       - '[[ "{{.CURRENT_PROJECT_ID}}" == "{{.PROJECT_ID}}" ]]'
 
+  ssh-keys:
+    deps:
+      - :install:software:gh
+      - :install:software:jq
+    cmds:
+      - .config/log info 'Clearing GitLab SSH keys'
+      - |
+        ACCEPT_HEADER="Accept: application/vnd.github+json"
+        GH_KEYS_URL="https://api.github.com/user/keys"
+        KEYIDS="$(curl -sSL -H "$ACCEPT_HEADER" -H "Authorization: token $GITHUB_TOKEN" "$GH_KEYS_URL" | jq '.[].id')"
+        for KEYID in $KEYIDS; do
+          curl -H "$ACCEPT_HEADER" -H "Authorization: token $GITHUB_TOKEN" -X DELETE "$GH_KEYS_URL/$KEYID"
+        done
+      - .config/log start 'Syncing SSH keys with GitHub'
+      - |
+        for KEY in `ls $HOME/.ssh/*.pub`; do
+          TITLE="$(cat $KEY | sed 's/\(.*\=\) \(.*\)$/\2/')"
+          gh ssh-key add $KEY -t "$TITLE"
+        done
+      - .config/log success 'Finished syncing SSH keys with GitHub'
+    preconditions:
+      - sh: '[ -n "$GITHUB_TOKEN" ]'
+        msg: The GITHUB_TOKEN must be set to a personal access token.
+
   update:
+    run: once
+    cmds:
+      - task: update:deps
+    status:
+      - '[ -z "$GITHUB_TOKEN" ]'
+
+  update:deps:
     deps:
       - update:meta
       - ids
diff --git a/roles/misc/nexus3-oss/.config/taskfiles/git/Taskfile-gitlab.yml b/roles/misc/nexus3-oss/.config/taskfiles/git/Taskfile-gitlab.yml
--- a/roles/misc/nexus3-oss/.config/taskfiles/git/Taskfile-gitlab.yml
+++ b/roles/misc/nexus3-oss/.config/taskfiles/git/Taskfile-gitlab.yml
@@ -15,7 +15,7 @@ tasks:
         sh: glab api projects/:fullpath | jq '.id'
       REQUEST_DATA: '{ "name":"PROJECT_CI_ACCESS_TOKEN", "scopes":["write_repository", "read_repository"] }'
       TOKEN_STATUS:
-        sh: glab api projects/:fullpath/access_tokens | jq -r '.[] | select(.name=="PROJECT_CI_ACCESS_TOKENX") | .id'
+        sh: type glab > /dev/null && glab api projects/:fullpath/access_tokens | jq -r '.[] | select(.name=="PROJECT_CI_ACCESS_TOKENX") | .id' || true
     run: once
     log:
       error: Failed to configure project-specific access token
@@ -27,7 +27,7 @@ tasks:
         'Content-Type:application/json' --data '{{.REQUEST_DATA}}' \
         'https://gitlab.com/api/v4/projects/{{.REPO_ID}}/access_tokens' > /dev/null
     status:
-      - '[ -n "{{.TOKEN_STATUS}}" ]'
+      - '[ -n "{{.TOKEN_STATUS}}" ] || ! glab api projects/:fullpath/access_tokens'
 
   branches:
     deps:
@@ -113,9 +113,10 @@ tasks:
           NO_PROMPT=1 glab repo create '{{.GITLAB_PATH}}' --group '{{.GITLAB_GROUP}}' \
           --description '{{.EMOJI_START}}{{.DESCRIPTION}}{{.EMOJI_END}}' --name '{{.NAME}}' \
           {{.PROJECT_TYPE}} --tag "$(jq -r '.keywords | tostring' package.json | sed 's/\[//' | sed 's/\]//')"
+          task --list > /dev/null || (echo "ERROR: Invalid Taskfiles!" && exit 1)
           git add --all
           HUSKY=0 git commit --quiet -m "🎂 Birth" -n || true
-          git push --quiet -u --no-progress gitlab master
+          git push gitlab master
         ignore_error: true
     status:
       - '[ -z "$GITLAB_TOKEN" ] || (test -d .git && glab repo view "{{.GITLAB_PATH}}" > /dev/null)'
@@ -166,10 +167,24 @@ tasks:
         wait){{else}}){{end}}
 
   group:exec:prompt:
+    deps:
+      - :install:software:glab
+      - :install:software:jq
     interactive: true
     cmds:
-      - mkdir -p .cache
-      - node .config/scripts/prompts/gitlab-group.js
+      - |
+        GITLAB_GROUPS="$(glab api --paginate groups | jq -r '.[].full_path')"
+        GROUP_OPTION="$(gum choose "$ENVIRONMENT_OPTIONS")"
+        GUM_CONFIRM_MSG="Would you like to use the previously run script (i.e. .cache/gitlab-group.sh)?"
+        if [ -f .cache/gitlab-group.sh ] && gum confirm "$GUM_CONFIRM_MSG"; then
+          bash .cache/gitlab-group.sh
+        else
+          TMP="$(mktemp)"
+          gum write --placeholder "Enter the script you would like to run including the hashbang (CTRL+D to finish)" --show-cursor-line --show-line-numbers > "$TMP"
+          bash "$TMP"
+          mkdir -p .cache
+          mv "$TMP" > .cache/gitlab-group.sh
+        fi
 
   group:repositories:
     deps:
@@ -329,7 +344,61 @@ tasks:
       - sh: '[ ! -z "$GITLAB_TOKEN" ]'
         msg: The `GITLAB_TOKEN` environment variable must be set to run this task
 
+  protected:off:
+    deps:
+      - :install:software:glab
+    vars:
+      BRANCH: '{{if .BRANCH}}{{.BRANCH}}{{else}}{{.CLI_ARGS}}{{end}}'
+    todo: figure out how to do it without deleteing the protection first
+    cmds:
+      - glab api projects/:fullpath/protected_branches/{{.BRANCH}} -X DELETE
+      - glab api projects/:fullpath/protected_branches -X POST -f name={{.BRANCH}} -f allow_force_push=true > /dev/null
+    status:
+      - '[ -z "$GITLAB_TOKEN" ]'
+
+  protected:on:
+    deps:
+      - :install:software:glab
+    vars:
+      BRANCH: '{{if .BRANCH}}{{.BRANCH}}{{else}}{{.CLI_ARGS}}{{end}}'
+    todo: figure out how to do it without deleteing the protection first
+    cmds:
+      - glab api projects/:fullpath/protected_branches/{{.BRANCH}} -X DELETE
+      - glab api projects/:fullpath/protected_branches -X POST -f name={{.BRANCH}} -f allow_force_push=false > /dev/null
+    status:
+      - '[ -z "$GITLAB_TOKEN" ]'
+
+  ssh-keys:
+    deps:
+      - :install:software:glab
+      - :install:software:jq
+    cmds:
+      - .config/log info 'Clearing GitLab SSH keys'
+      - |
+        KEY_URL='https://gitlab.com/api/v4/user/keys'
+        KEYIDS="$(curl -sSL --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "$KEY_URL" | jq '.[].id')"
+        for KEYID in $KEYIDS; do
+          curl --header "PRIVATE-TOKEN: $GITLAB_TOKEN" -X DELETE "$KEY_URL/$KEYID"
+        done
+      - .config/log start 'Syncing SSH keys with GitLab'
+      - |
+        for KEY in `ls $HOME/.ssh/*.pub`; do
+          TITLE="$(cat $KEY | sed 's/\(.*\=\) \(.*\)$/\2/')"
+          glab ssh-key add $KEY -t "$TITLE"
+        done
+      - .config/log success 'Finished syncing SSH keys with GitLab'
+    preconditions:
+      - sh: '[ -n "$GITLAB_TOKEN" ]'
+        msg: The GITLAB_TOKEN must be set to a personal access token.
+
   update:
+    run: once
+    cmds:
+      - task: update:deps
+    status:
+      - '[ -z "$GITLAB_TOKEN" ] || ! type glab &> /dev/null'
+
+  update:deps:
     deps:
       - access-token
       - branches
diff --git a/roles/misc/nexus3-oss/.config/taskfiles/git/Taskfile.yml b/roles/misc/nexus3-oss/.config/taskfiles/git/Taskfile.yml
--- a/roles/misc/nexus3-oss/.config/taskfiles/git/Taskfile.yml
+++ b/roles/misc/nexus3-oss/.config/taskfiles/git/Taskfile.yml
@@ -4,7 +4,7 @@ version: '3'
 vars:
   EMOJI_END:
     sh: |
-      if [ -f '.variables.json' ]; then
+      if [ -f '.variables.json' ] && type jq &> /dev/null; then
         BP_END="$(jq -r '.emoji_end' .variables.json)"
         if [ "$BP_END" != 'null' ]; then
           echo "$BP_END"
@@ -18,7 +18,7 @@ vars:
       fi
   EMOJI_START:
     sh: |
-      if [ -f '.variables.json' ]; then
+      if [ -f '.variables.json' ] && type jq &> /dev/null; then
         BP_START="$(jq -r '.emoji_start' .variables.json)"
         if [ "$BP_START" != 'null' ]; then
           echo "$BP_START"
@@ -40,15 +40,18 @@ env:
 
 tasks:
   commit:automated:
+    deps:
+      - remotes
     log:
       start: Running automated commit
     cmds:
-      - cmd: |
-          if [[ "$FULLY_AUTOMATED_TASKS" == 'true' ]]; then
-            git add --all
-            HUSKY=0 git commit -m "☁️ Automation" -n
-          fi
+      - task --list > /dev/null || (echo "ERROR > Invalid Taskfile(s)!" && exit 1)
+      - git add --all
+      - cmd: >
+          HUSKY=0 git commit -m "☁️ chore(automation): Automated update" -n
         ignore_error: true
+    status:
+      - '[ "$FULLY_AUTOMATED_TASKS" != "true" ] || [ "$SEMANTIC_RELEASE" == "true" ]'
 
   convert:folder:submodule:
     deps:
@@ -67,18 +70,15 @@ tasks:
       - git init
       - git remote add origin "{{.GITLAB_REPO}}"
       - git add --all
-      - git commit --quiet -m "refactor(convert-dir-to-submodule) Adding folder/project to its own git repository."
+      - git commit --quiet -m "🧐 refactor(submodule): Adding folder/project to its own git repository."
       - git push --quiet -u --no-progress origin master
-      - |
-        cd ..
-        rm -rf {{.BASENAME}}
-        git add {{.BASENAME}}
-        git commit --quiet -m "refactor(convert-dir-to-submodule) Removing folder which will now be a submodule."
-        git submodule add -b master "{{.GITLAB_REPO}}" {{.BASENAME}}
-        git add {{.BASENAME}}
-        git commit --quiet -m "refactor(convert-dir-to-submodule) Adding new submodule which was previously a directory."
-        git push --quiet -u --no-progress origin HEAD
-      - .config/log success ''
+      - cd .. && rm -rf {{.BASENAME}}
+      - cd .. && git add {{.BASENAME}}
+      - cd .. && git commit --quiet -m "🧐 refactor(submodule): Removing folder which will now be a submodule."
+      - cd .. && git submodule add -b master "{{.GITLAB_REPO}}" {{.BASENAME}}
+      - cd .. && git add {{.BASENAME}}
+      - cd .. && git commit --quiet -m "🧐 refactor(submodule): Adding new submodule which was previously a directory."
+      - cd .. && git push --quiet -u --no-progress origin HEAD
     preconditions:
       - sh: '[[ ! $(git rev-parse --git-dir) =~ ".git/modules" ]]'
         msg: Cannot convert the directory to a submodule - the directory already appears to be a submodule.
@@ -86,6 +86,17 @@ tasks:
   convert:folder:subrepo:
     deps:
       - :install:software:subrepo
+    summary: |
+      # Convert Folder to Sub-repo
+
+      This task will work if you have Taskfiles set up in a sub-directory of a project
+      that is already a git repository. Instead of using sub-modules, this method makes
+      the main repository's structure look as if no sub-module wizardry is going on.
+
+      To use this task, go into a sub-directory that you want to make a git subrepo and
+      then run `task git:convert:folder:subrepo` while making sure that the
+      `FULLY_AUTOMATED_TASKS` variables is set equal to `true`. There may be other
+      tokens required for accessing the APIs of GitHub, GitLab, etc.
     vars:
       BASENAME:
         sh: basename "$PWD"
@@ -97,31 +108,62 @@ tasks:
       success: Converted `{{.BASENAME}}` into a sub-repo
     cmds:
       - rm -rf .git
+      - git config url."git@gitlab.com:".insteadOf "https://gitlab.com/"
+      - git config url."git@github.com:".insteadOf "https://github.com/"
+      - task: commit:automated
       - |
         ROLE_DIR="$PWD"
         while ! test -d .git; do cd ..; done
-        git remote add {{.BASENAME}} {{.GITLAB_REPO}}
+        if ! git remote get-url {{.BASENAME}} &> /dev/null; then
+          git remote add {{.BASENAME}} {{.GITLAB_REPO}}
+        fi
         RELATIVE_DIR="$(echo $ROLE_DIR | sed 's@'"$PWD"'/@@')"
-        HUSKY=0 git subrepo clone {{.BASENAME}} "$RELATIVE_DIR" -b master
+        task git:commit:automated
+        HUSKY=0 git subrepo init "$RELATIVE_DIR" -r {{.BASENAME}} -b master
+    status:
+      - '[ "$FULLY_AUTOMATED_TASKS" != "true" ]'
 
   filter:
+    deps:
+      - :install:software:bfg
+    desc: Remove large unnecessary and large files from the repository
+    summary: |
+      # Clean Up Git Repository
+
+      This task will remove files that may have been committed by accident like node_modules.
+      It will also use [bfg](https://rtyley.github.io/bfg-repo-cleaner/) to remove all files
+      that are over 50MB.
     log:
       error: Error filtering git history
       start: Filtering unnecessary items from git history
       success: Successfully filtered unnecessary items from git history
     cmds:
       - git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch -r **/node_modules/' --prune-empty -- --all
+      - bfg --strip-blobs-bigger-than 50M
 
   push:all:
+    deps:
+      - :ci:commit:config
+      - :git:github:create
+      - :git:gitlab:create
     log:
       error: Encountered error while running `git push all master --force || git push origin master`
       start: Running `git push all master --force || git push origin master`
       success: Successfully ran `git push all master --force || git push origin master`
     cmds:
       - |
-        if [[ "$FULLY_AUTOMATED_TASKS" == 'true' ]]; then
-          git push all master --force || git push origin master
+        if ! git push all master --force; then
+          git pull -X theirs origin master
+          git add --all
+          HUSKY=0 git commit -m "☁️ chore(automation): Automated update to all remotes" -n
+          if ! git push all master --force; then
+            task git:gitlab:protected:off -- "master"
+            git push all master --force
+            task git:gitlab:protected:on -- "master"
+          fi
         fi
+    status:
+      - '[ -n "$CI" ] || [ "$SEMANTIC_RELEASE" == "true" ] || [ "$FULLY_AUTOMATED_TASKS" != "true" ]'
 
   remotes:
     deps:
@@ -185,9 +227,9 @@ tasks:
           .config/log success 'Added git remote named `all`'
         fi
     status:
-      - '[[ "$(git config remote.all.url)" == "${GITLAB_REPO}.git" ]] || [[ "${container:=}" == "docker" ]]'
-      - '[[ "$(git config remote.github.url)" == "${GITHUB_REPO}.git" ]] || [[ "${container:=}" == "docker" ]]'
-      - '[[ "$(git config remote.gitlab.url)" == "${GITLAB_REPO}.git" ]] || [[ "${container:=}" == "docker" ]]'
+      - '[[ "$(git config remote.all.url)" == "${GITLAB_REPO}.git" ]] || [ -n "$CI" ]'
+      - '[[ "$(git config remote.github.url)" == "${GITHUB_REPO}.git" ]] || [ -n "$CI" ]'
+      - '[[ "$(git config remote.gitlab.url)" == "${GITLAB_REPO}.git" ]] || [ -n "$CI" ]'
 
   remove:history:cli:
     deps:
@@ -260,17 +302,21 @@ tasks:
 
   update:
     cmds:
-      - task: :git:gitlab:create
-      - task: :git:github:create
-      - task: update:continue
+      - task: update:start
+    status:
+      - '[ "$FULLY_AUTOMATED_TASKS" != "true" ]'
 
-  update:continue:
+  update:finish:
     deps:
       - :git:gitlab:update
       - :git:github:update
+    run: once
+
+  update:start:
+    run: once
     cmds:
-      - |
-        if ! git push -u origin master; then
-          git pull origin master --allow-unrelated-histories
-          git push origin -u origin master
-        fi
+      - task: :git:gitlab:create
+      - task: :git:github:create
+      - task: update:finish
+    status:
+      - '[ -n "$CI" ] || ([ -z "$GITLAB_TOKEN" ] && [ -z "$GITHUB_TOKEN" ])'
