⤵️ chore(synchronize) Applying changes from upstream repository.

diff --git a/.config/taskfiles/ci/Taskfile.yml b/.config/taskfiles/ci/Taskfile.yml
--- a/.config/taskfiles/ci/Taskfile.yml
+++ b/.config/taskfiles/ci/Taskfile.yml
@@ -72,24 +72,27 @@ tasks:
   commit:
     deps:
       - :install:software:git
+    vars:
+      CURR_BRANCH:
+        sh: git rev-parse --abbrev-ref HEAD
     log:
-      error: Encountered error while pushing changes to master
-      start: Bypassing git hooks and pushing changes to master (if there are any changes)
+      error: Encountered error while pushing changes to {{.CURR_BRANCH}}
+      start: Bypassing git hooks and pushing changes to {{.CURR_BRANCH}} (if there are any changes)
     cmds:
       - task: commit:config
       - task: lockfiles:clean
-      - |
-        task --list > /dev/null || (echo "ERROR: Invalid Taskfiles!" && exit 1)
-        git add --all
+      - task --list > /dev/null || (echo "ERROR Invalid Taskfiles!" && exit 1)
+      - git add --all
       - git diff --cached "*"
       - |
         if [[ $(git status --porcelain) ]]; then
-          git commit -m "⤵️ automation(synchronize) Applying changes from upstream repository."
-          git push -q -o ci.skip origin master || FAILED_PUSH=$?
+          git commit -m "⤵️ chore(synchronize) Applying changes from upstream repository."
+          git push -q -o ci.skip origin {{.CURR_BRANCH}} || FAILED_PUSH=$?
           if [ -n "$FAILED_PUSH" ]; then
-            git pull origin master
+            git pull -X theirs origin {{.CURR_BRANCH}}
             task --list &> /dev/null || (echo "ERROR: Invalid Taskfiles!" && exit 1)
-            git push --force -q -o ci.skip origin master
+            git commit -m "⤵️ chore(synchronize-merge) Merging changes from upstream repository with -X theirs."
+            git push --force -q -o ci.skip origin {{.CURR_BRANCH}}
           fi
         fi
     status:
