☁️ Automation

diff --git a/.config/taskfiles/ci/Taskfile.yml b/.config/taskfiles/ci/Taskfile.yml
--- a/.config/taskfiles/ci/Taskfile.yml
+++ b/.config/taskfiles/ci/Taskfile.yml
@@ -10,6 +10,8 @@ tasks:
       - task: checkout
       - task: lockfiles
       - task: before:npm
+    status:
+      - '[ -z "$CI" ]'
 
   before:npm:
     deps:
@@ -22,20 +24,49 @@ tasks:
       - pnpm config set store-dir .pnpm-store
 
   checkout:
+    deps:
+      - :install:software:git
     log:
       error: Failed to pull latest changes
       start: Pulling latest changes
       success: Successfully pulled latest changes
     cmds:
-      - git fetch --all --tags -f
+      - git pull
       - |
-        if [[ "$CI_COMMIT_REF_NAME" == 'synchronize' ]]; then
-          git checkout -q master
-          git pull -q origin master
+        if [ "$CI_COMMIT_REF_NAME" == 'synchronize' ]; then
+          git checkout master
+          git pull origin master
         else
-          git checkout -q "$CI_COMMIT_REF_NAME"
-          git pull -q origin "$CI_COMMIT_REF_NAME"
+          git checkout "$CI_COMMIT_REF_NAME"
+          git pull origin "$CI_COMMIT_REF_NAME"
         fi
+    status:
+      - '[ -n "$NO_GIT_CREDS" ]'
+
+  codeclimate:
+    deps:
+      - :install:software:docker
+    log:
+      error: Encountered error while running CodeClimate for CI
+      start: Running CodeClimate for CI
+      success: Successfully finished running CodeClimate for CI
+    cmds:
+      - |
+        if [ -f .config/codeclimate.yml ]; then
+          cp .config/codeclimate.yml .codeclimate.yml
+        else
+          curl -sSL https://gitlab.com/megabyte-labs/common/shared/-/raw/master/.config/codeclimate.yml > .codeclimate.yml
+        fi
+      - docker pull codeclimate/codeclimate
+      - task: :lint:codeclimate:load:custom-engines
+      - task: codeclimate:gitlab
+
+  codeclimate:gitlab:
+    cmds:
+      - docker run --rm --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock
+        --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze --dev -f json > gl-code-quality-report.json
+    status:
+      - '[ -z "$GITLAB_CI" ]'
 
   commit:
     deps:
@@ -46,30 +77,37 @@ tasks:
     cmds:
       - task: commit:config
       - task: lockfiles:clean
-      - git add --all
+      - |
+        task --list > /dev/null || (echo "ERROR: Invalid Taskfiles!" && exit 1)
+        git add --all
       - git diff --cached "*"
       - |
         if [[ $(git status --porcelain) ]]; then
           git commit -m "⤵️ automation(synchronize) Applying changes from upstream repository."
-          git push -q -o ci.skip origin master
+          git push -q -o ci.skip origin master || FAILED_PUSH=$?
+          if [ -n "$FAILED_PUSH" ]; then
+            git pull origin master
+            task --list &> /dev/null || (echo "ERROR: Invalid Taskfiles!" && exit 1)
+            git push --force -q -o ci.skip origin master
+          fi
         fi
+    status:
+      - '[ -z "$CI" ] || [ -n "$NO_GIT_CREDS" ]'
 
   commit:config:
     deps:
       - :install:software:git
+    run: once
+    log:
+      error: Error configuring git
+      start: Configuring git to use CI-friendly parameters
+      success: Successfully configured git to use CI parameters
     cmds:
       - git remote set-url origin "https://root:$GROUP_ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
       - git config user.email "$GITLAB_CI_EMAIL"
       - git config user.name "$GITLAB_CI_NAME"
-    preconditions:
-      - sh: '[[ ! -z "$GROUP_ACCESS_TOKEN" ]]'
-        msg: The `GROUP_ACCESS_TOKEN` GitLab CI variable must be set to an API key with priviledges to read/write to repositories.
-      - sh: '[[ ! -z "$GITLAB_CI_EMAIL" ]]'
-        msg: 'The `GITLAB_CI_EMAIL` GitLab CI variable must be set to the e-mail address you would like associated with
-          automated commits (e.g. "help@mydomain.com").'
-      - sh: '[[ ! -z "$GITLAB_CI_NAME" ]]'
-        msg: 'The `GITLAB_CI_NAME` GitLab CI variable must be set to the name you would like associated with automated commits
-          (e.g. "CI Automation").'
+    status:
+      - '[ -z "$GROUP_ACCESS_TOKEN" ] || [ -z "$GITLAB_CI_EMAIL" ] || [ -z "$GITLAB_CI_NAME" ] || [ -z "$GITLAB_CI" ]'
 
   lockfiles:
     cmds:
@@ -103,24 +141,37 @@ tasks:
     cmds:
       - >
         git submodule foreach 'git config user.email "$GITLAB_CI_EMAIL"; git config user.name "$GITLAB_CI_NAME";
-        git checkout -q master; git pull -q origin master --ff-only'
+        DEFAULT_BRANCH="$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')";
+        git checkout -q "$DEFAULT_BRANCH"; git pull -q origin "$DEFAULT_BRANCH" --ff-only'
+    status:
+      - '[ -z "$CI" ] || [ -n "$NO_GIT_CREDS" ]'
 
   synchronize:
+    deps:
+      - commit:config
     log:
       error: Failed to update the `synchronize` branch
       start: Synchronizing the `synchronize` branch with the `master` branch
       success: Successfully updated the `synchronize` branch
     cmds:
+      - git fetch origin
       - git checkout -b synchronize || git checkout synchronize
       - git reset --hard HEAD
       - git pull -q origin master
-      - git push -q -o ci.skip origin synchronize --force
       - |
-        if [ '{{.REPOSITORY_TYPE}}' == 'deprecated_common' ] && [ '{{.REPOSITORY_SUBTYPE}}' == 'shared' ]; then
-          .config/log info 'Bypassing the `master` branch pipeline trigger because the repository is not of the right type'
-        else
-          .config/log info 'Triggering the `master` branch pipeline'
-          curl -s --request POST --form "token=${CI_JOB_TOKEN}" --form ref=master --form "variables[PIPELINE_SOURCE]=$PIPELINE_SOURCE" \
-            "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/trigger/pipeline"
+        git push --force -q -o ci.skip origin synchronize || FAILED_SYNC=$?
+        if [ -n "$FAILED_SYNC" ]; then
+          task git:gitlab:protected:off -- "synchronize"
+          git push --force -q -o ci.skip origin synchronize
         fi
+      - task: synchronize:gitlab
       - git checkout master
+    status:
+      - '[ -n "$NO_GIT_CREDS" ]'
+
+  synchronize:gitlab:
+    cmds:
+      - curl -s --request POST --form "token=${CI_JOB_TOKEN}" --form ref=master --form "variables[PIPELINE_SOURCE]=$PIPELINE_SOURCE"
+        "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/trigger/pipeline"
+    status:
+      - '[ -z "$GITLAB_CI" ] || [ -n "$NO_SYNCHRONIZE" ]'
diff --git a/.config/taskfiles/docker/Taskfile-update.yml b/.config/taskfiles/docker/Taskfile-update.yml
--- a/.config/taskfiles/docker/Taskfile-update.yml
+++ b/.config/taskfiles/docker/Taskfile-update.yml
@@ -30,12 +30,16 @@ tasks:
     vars:
       AUTHORS:
         sh: jq -r '.docker_label_authors' .variables.json
+      DESCRIPTION:
+        sh: jq -r '.description' package.json
       HELP_EMAIL:
         sh: jq -r '.email.help' .variables.json
       LICENSE:
         sh: jq -r '.license' .variables.json
       ORGANIZATION:
         sh: jq -r '.organization' .variables.json
+      SOURCE:
+        sh: jq -r '.blueprint.repository.github' package.json
       URL:
         sh: jq -r '.link.home' .variables.json
     log:
@@ -51,11 +55,11 @@ tasks:
         echo 'LABEL maintainer="{{.ORGANIZATION}} <{{.HELP_EMAIL}}>"' >> Dockerfile
         echo 'LABEL org.opencontainers.image.authors="{{.AUTHORS}}"' >> Dockerfile
         echo 'LABEL org.opencontainers.image.created=$BUILD_DATE' >> Dockerfile
-        echo 'LABEL org.opencontainers.image.description="[[ Injected by running `task update` ]]"' >> Dockerfile
-        echo 'LABEL org.opencontainers.image.documentation="[[ Injected by running `task update` ]]"' >> Dockerfile
+        echo 'LABEL org.opencontainers.image.description="{{.DESCRIPTION}}"' >> Dockerfile
+        echo 'LABEL org.opencontainers.image.documentation="{{.SOURCE}}/blob/master/README.md"' >> Dockerfile
         echo 'LABEL org.opencontainers.image.licenses="{{.LICENSE}}"' >> Dockerfile
         echo 'LABEL org.opencontainers.image.revision=$REVISION' >> Dockerfile
-        echo 'LABEL org.opencontainers.image.source="[[ Injected by running `task update` ]]"' >> Dockerfile
+        echo 'LABEL org.opencontainers.image.source="{{.SOURCE}}"' >> Dockerfile
         echo 'LABEL org.opencontainers.image.url="{{.URL}}"' >> Dockerfile
         echo 'LABEL org.opencontainers.image.vendor="{{.ORGANIZATION}}"' >> Dockerfile
         echo 'LABEL org.opencontainers.image.version=$VERSION' >> Dockerfile
@@ -90,8 +94,48 @@ tasks:
       - sed -i "s^.*org.opencontainers.image.description.*^LABEL org.opencontainers.image.description=\"${DESCRIPTION}\"^g" Dockerfile
       - sed -i "s^.*org.opencontainers.image.documentation.*^LABEL org.opencontainers.image.documentation=\"${REPOSITORY_GITHUB}/blob/master/README.md\"^g" Dockerfile
       - sed -i "s^.*org.opencontainers.image.licenses.*^LABEL org.opencontainers.image.licenses=\"{{.LICENSE}}\"^g" Dockerfile
-      - sed -i "s^.*org.opencontainers.image.source.\*^LABEL org.opencontainers.image.source=\"${REPOSITORY_GITHUB}.git\"^g" Dockerfile
-      - sed -i "s^.*org.opencontainers.image.url.\*^LABEL org.opencontainers.image.url=\"{{.URL}}\"^g" Dockerfile
-      - sed -i "s^.*org.opencontainers.image.vendor.\*^LABEL org.opencontainers.image.vendor=\"{{.ORGANIZATION}}\"^g" Dockerfile
-# yamllint enable rule:line-length
-# eslint-enable max-len
+      - sed -i "s^.*org.opencontainers.image.source.*^LABEL org.opencontainers.image.source=\"${REPOSITORY_GITHUB}.git\"^g" Dockerfile
+      - sed -i "s^.*org.opencontainers.image.url.*^LABEL org.opencontainers.image.url=\"{{.URL}}\"^g" Dockerfile
+      - sed -i "s^.*org.opencontainers.image.vendor.*^LABEL org.opencontainers.image.vendor=\"{{.ORGANIZATION}}\"^g" Dockerfile
+  # yamllint enable rule:line-length
+  # eslint-enable max-len
+
+  sort:
+    todo: Make this remove duplicates using a command like `uniq -u`
+    log:
+      error: Encountered error while sorting `*.txt` files in the `./local` folder`
+      start: Sorting, removing empty lines, and removing duplicate lines from all `*.txt` files in the `./local` folder
+      success: Successfully sorted `*.txt` files in the `./local` folder
+    cmds:
+      - find ./local -type f -name '*.txt' -exec sort {} -o {} \; -exec sed -i '/^$/d' {} \;
+    status:
+      - '! find ./local -type f -name "*.txt" | grep txt'
+
+  version:
+    deps:
+      - :install:software:jq
+    vars:
+      VERSION_COMMAND:
+        sh: jq -r '.blueprint.versionCommand' package.json
+    log:
+      error: Error acquiring software version
+      start: Acquiring software version
+      success: Finished software version acquisition sequence
+    cmds:
+      - docker build --tag {{.DOCKER_IMAGE}}:latest  --target "{{.DOCKER_BASE_TAG}}" .
+      - |
+        VERSION="$({{.VERSION_COMMAND}})" || EXIT_CODE=$?
+        if [ -n "$EXIT_CODE" ]; then
+          .config/log warn 'Failed to run version command (`{{.VERSION_COMMAND}}`) - will retry after images are finished building'
+        else
+          CURR_VERSION="$(jq -r '.version' package.json)"
+          TMP="$(mktemp)"
+          jq --arg version "$(jq --arg v "$VERSION" '$v' package.json |  sed 's/^[^0-9]*//' | sed 's/[^0-9]*$//')" '.version = $version' package.json > "$TMP"
+          mv "$TMP" package.json
+          if [ "$CURR_VERSION" != "$(jq -r '.version' package.json)" ]; then
+            .config/log info 'Updating documentation with new software version'
+            task common:update:update
+          fi
+        fi
+    status:
+      - '[ "{{.VERSION_COMMAND}}" == "null" ] || [ "{{.DOCKER_BASE_TAG}}" != "{{.CLI_ARGS}}" ]'
diff --git a/.config/taskfiles/docker/Taskfile.yml b/.config/taskfiles/docker/Taskfile.yml
--- a/.config/taskfiles/docker/Taskfile.yml
+++ b/.config/taskfiles/docker/Taskfile.yml
@@ -2,11 +2,31 @@
 version: '3'
 
 vars:
+  DIND_MOUNT_MAPPING: /var/run/docker.sock:/var/run/docker.sock
+  DOCKER_BASE_TAG:
+    sh: |
+      if [ -f Dockerfile ] && type jq &> /dev/null; then
+        BASE_TAG="$(jq -r '.blueprint.dockerBaseTag' package.json)"
+        if [ "$BASE_TAG" != 'null' ]; then
+          echo "$BASE_TAG"
+        else
+          if grep -m1 "^FROM .* AS .*" Dockerfile > /dev/null; then
+            FIRST_LINE=$(head -n 1 Dockerfile | sed 's/.* AS \(.*\)/\1/')
+            if [ -n "$FIRST_LINE" ]; then
+              echo "$FIRST_LINE"
+            else
+              echo ""
+            fi
+          else
+            echo ""
+          fi
+        fi
+      fi
   DOCKER_IMAGE:
     sh: |
-      echo "{{.DOCKERHUB_PROFILE}}/{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}$(jq -r '.blueprint.slug' package.json){{end}}"
-  SLIM_ENABLED:
-    sh: jq -r '.blueprint.dockerSlimCommand' package.json | sed 's/null/false/'
+      if type jq &> /dev/null; then
+        echo "{{.DOCKERHUB_PROFILE}}/$(jq -r '.blueprint.slug' package.json)"
+      fi
 
 tasks:
   build:
@@ -24,22 +44,50 @@ tasks:
       a `Docker.build1.test.yml` and `Docker.build2.test.yml` container-structure-test.
     hide:
       sh: '[ ! -f Dockerfile ]'
+    log:
+      error: Encountered error while running Docker build sequence
+      start: Running Docker build sequence
+      success: Finished running Docker build sequence
     cmds:
+      - task: taskfile:deps
       - |
-        if [ -f Docker.test.yml ]; then
-          task docker:build:fat
-          if [ "$(jq -r '.blueprint.dockerSlimCommand' package.json)" != 'null' ]; then
+        if [ -d ./test/structure ]; then
+          TESTS="$(find ./test/structure -mindepth 1 -maxdepth 1 -type f -name "*.yml")"
+          if echo "$TESTS" | grep '.yml' > /dev/null; then
+            for TEST_FILE in $TESTS; do
+              TARGET="$(echo "$TEST_FILE" | sed 's/.*\/\([^\/]*\).yml$/\1/')"
+              if [ "$(jq --arg slug "$TARGET" '.blueprint.dockerSlimCommand | type' package.json)" == 'object' ]; then
+                if [ "$(jq --arg slug "$TARGET" '.blueprint.dockerSlimCommand[$slug]' package.json)" != 'null' ]; then
+                  task docker:build:slim -- "$TARGET"
+                else
+                  .config/log warn 'The `.blueprint.dockerSlimCommand` is missing - skipping slim build and building just a regular image'
+                  task docker:build:fat -- "$TARGET"
+                fi
+              else
+                if [ "$(jq --arg slug "$TARGET" '.blueprint.dockerSlimCommand' package.json)" != 'null' ]; then
+                  task docker:build:slim -- "$TARGET"
+                else
+                  task docker:build:fat -- "$TARGET"
+                fi
+              fi
+            done
+          else
+            .config/log error 'The `./test/structure` folder is present but there are no container-structure-tests in it. Add tests \
+            for each build target in the `Dockerfile` that you would like to generate an image for.'
+            exit 1
+          fi
+        else
+          .config/log info 'No `./test/structure` folder is present so assuming there is only one build target'
+          if [ "$(jq -r '.blueprint.dockerSlimCommand' package.json)" != null ]; then
+            .config/log info '`.blueprint.dockerSlimCommand` is present in `package.json` so building both a `latest` and `slim` image'
             task docker:build:slim
+          else
+            task docker:build:fat
           fi
         fi
-      - |
-        for TESTFILE in Docker.*.test.yml; do
-          if [ "$TESTFILE" != 'Docker.*.test.yml' ]; then
-            TEST_IMAGE_SLUG="$(echo $TESTFILE | sed 's/^Docker.//' | sed 's/.test.yml$//')"
-            task docker:build:fat -- "$TEST_IMAGE_SLUG"
-            task docker:build:slim -- "$TEST_IMAGE_SLUG"
-          fi
-        done
+    preconditions:
+      - sh: test -f Dockerfile
+        msg: The `Dockerfile` must be present in order to build it
 
   login:
     deps:
@@ -74,21 +122,35 @@ tasks:
       a `Docker.build1.test.yml` and `Docker.build2.test.yml` container-structure-test.
     cmds:
       - |
-        if [ -f Docker.test.yml ]; then
+        if [ -d ./test/structure ]; then
+          TESTS="$(find ./test/structure -mindepth 1 -maxdepth 1 -type f -name "*.yml")"
+          if echo "$TESTS" | grep '.yml'; then
+            for TEST_FILE in $TESTS; do
+              TARGET="$(echo "$TEST_FILE" | sed 's/.*\/\([^\/]*\).yml$/\1/')"
+              task docker:publish:images -- "$TARGET"
+            done
+          else
+            .config/log error 'The `./test/structure` folder is present but there are no container-structure-tests in it. Add tests \
+            for each build target in the `Dockerfile` that you would like to generate an image for.'
+            exit 1
+          fi
+        else
+          .config/log info 'No `./test/structure` folder is present so assuming there is only one build target'
           task docker:publish:images
         fi
-      - |
-        for TESTFILE in Docker.*.test.yml; do
-          if [ "$TESTFILE" != 'Docker.*.test.yml' ]; then
-            TEST_IMAGE_SLUG="$(echo $TESTFILE | sed 's/^Docker.//' | sed 's/.test.yml$//')"
-            task docker:publish:images -- "$TEST_IMAGE_SLUG"
-          fi
-        done
+      - task: pushrm
 
   publish:image:
     vars:
-      SLUG:
-        sh: echo "{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}$(jq -r '.blueprint.slug' package.json){{end}}"
+      SLIM_ENABLED:
+        sh: |
+          TYPE="$(jq -r '.blueprint.dockerSlimCommand | type' package.json)"
+          if [ "$TYPE" != 'object' ]; then
+            jq -r '.blueprint.dockerSlimCommand' package.json | sed 's/null/false/'
+          else
+            TARGET="{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}{{.TARGET}}{{end}}"
+            jq --arg target "$TARGET" -r '.blueprint.dockerSlimCommand[$target]' package.json | sed 's/null/false/'
+          fi
     log:
       error: Failed to tag / push `{{.DOCKER_IMAGE}}:{{.TARGET_TAG}}`
       start: Tagging and pushing `{{.DOCKER_IMAGE}}:{{.TARGET_TAG}}`
@@ -96,21 +158,16 @@ tasks:
     cmds:
       - docker tag {{.DOCKER_IMAGE}}:{{.SOURCE_TAG}} {{.DOCKER_IMAGE}}:{{.TARGET_TAG}}
       - docker push {{.DOCKER_IMAGE}}:{{.TARGET_TAG}}
-      - |
-        if [ '{{.REPOSITORY_SUBTYPE}}' == 'codeclimate' ] && echo '{{.SLUG}}' | grep 'codeclimate-'; then
-          .config/log info 'Uploading to tag `{{.TARGET_TAG}}-codeclimate` since this is a codeclimate repository'
-          TARGET_IMAGE="$(echo '{{.SLUG}}' | sed 's/^codeclimate-//')"
-          docker tag {{.DOCKER_IMAGE}}:{{.SOURCE_TAG}} "{{.DOCKERHUB_PROFILE}}/${TARGET_IMAGE}:{{.TARGET_TAG}}-codeclimate"
-          docker push "{{.DOCKERHUB_PROFILE}}/${TARGET_IMAGE}:{{.TARGET_TAG}}-codeclimate"
-          .config/log success 'Uploaded tag `{{.TARGET_TAG}}-codeclimate` successfully'
-        fi
     status:
-      - if [[ '{{.SOURCE_TAG}}' == 'slim' ]]; then [[ '{{.SLIM_ENABLED}}' == 'false' ]]; fi
+      - '[[ "{{.SOURCE_TAG}}" == "slim"* ]]'
+      - '[[ "{{.SLIM_ENABLED}}" == "false" ]]'
 
   publish:images:
     vars:
       MAJOR_VERSION:
         sh: jq -r '.version' package.json | sed 's/\..*\..*$//'
+      TAG_POST: '{{if ne .DOCKER_BASE_TAG .CLI_ARGS}}-{{if (contains "codeclimate" .CLI_ARGS)}}codeclimate{{else}}{{.CLI_ARGS}}{{end}}{{end}}'
+      TARGET: '{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}{{.TARGET}}{{end}}'
       VERSION:
         sh: jq -r ".version" package.json
     log:
@@ -120,29 +177,28 @@ tasks:
     cmds:
       - task: publish:image
         vars:
-          SOURCE_TAG: latest
-          TARGET_TAG: '{{.VERSION}}'
+          SOURCE_TAG: latest{{.TAG_POST}}
+          TARGET_TAG: '{{.VERSION}}{{.TAG_POST}}'
       - task: publish:image
         vars:
-          SOURCE_TAG: latest
-          TARGET_TAG: '{{.MAJOR_VERSION}}-latest'
+          SOURCE_TAG: latest{{.TAG_POST}}
+          TARGET_TAG: '{{.MAJOR_VERSION}}-latest{{.TAG_POST}}'
       - task: publish:image
         vars:
-          SOURCE_TAG: latest
-          TARGET_TAG: latest
+          SOURCE_TAG: latest{{.TAG_POST}}
+          TARGET_TAG: latest{{.TAG_POST}}
       - task: publish:image
         vars:
-          SOURCE_TAG: slim
-          TARGET_TAG: '{{.VERSION}}-slim'
+          SOURCE_TAG: slim{{.TAG_POST}}
+          TARGET_TAG: '{{.VERSION}}-slim{{.TAG_POST}}'
       - task: publish:image
         vars:
-          SOURCE_TAG: slim
-          TARGET_TAG: '{{.MAJOR_VERSION}}-slim'
+          SOURCE_TAG: slim{{.TAG_POST}}
+          TARGET_TAG: '{{.MAJOR_VERSION}}-slim{{.TAG_POST}}'
       - task: publish:image
         vars:
-          SOURCE_TAG: slim
-          TARGET_TAG: slim
-      - task: pushrm
+          SOURCE_TAG: slim{{.TAG_POST}}
+          TARGET_TAG: slim{{.TAG_POST}}
 
   pushrm:
     deps:
@@ -186,6 +242,17 @@ tasks:
       answer:
         cmds:
           - docker run -v "${PWD}:/work" -w /work -it --entrypoint /bin/sh --rm {{.ANSWER}}
+
+  taskfile:deps:
+    vars:
+      DOCKER_TASKS_TAG:
+        sh: jq -r '.blueprint.dockerTasksTag' package.json
+    cmds:
+      - task: :common:util:task:tag:deps
+        vars:
+          TAG: '{{.DOCKER_TASKS_TAG}}'
+    status:
+      - '[ "{{.DOCKER_TASKS_TAG}}" == "null" ]'
 
   test:
     deps:
@@ -236,35 +303,14 @@ tasks:
       ## CodeClimate CLI Testing
 
       Any folder in the `test/` folder that starts with `codeclimate` gets scanned by CodeClimate CLI.
+    log:
+      error: Encountered error during Docker test sequence
+      start: Initiating Docker test sequence
+      success: Successfully completed Docker test sequence
     cmds:
-      - |
-        if [ -f Docker.test.yml ]; then
-          task docker:test:container-structure-test
-          if [ -d test-output ]; then
-            task docker:test:output
-          fi
-        fi
-      - |
-        for TESTFILE in Docker.*.test.yml; do
-          if [ "$TESTFILE" != 'Docker.*.test.yml' ]; then
-            TEST_IMAGE_SLUG="$(echo $TESTFILE | sed 's/^Docker.//' | sed 's/.test.yml$//')"
-            task docker:test:container-structure-test -- "$TEST_IMAGE_SLUG"
-          fi
-        done
-      - |
-        for FOLDER in test/codeclimate*/; do
-          if [ "$FOLDER" != 'test/codeclimate*/' ]; then
-            task lint:codeclimate -- " $FOLDER"
-          fi
-        done
-      - |
-        if [ -d test-output ]; then
-          for TESTFILE in Docker.*.test.yml; do
-            if [ "$TESTFILE" != 'Docker.*.test.yml' ]; then
-              task docker:test:output -- "$TEST_IMAGE_SLUG"
-            fi
-          done
-        fi
+      - task: :docker:test:container-structure-tests
+      - task: :docker:test:output
+      - task: :docker:test:codeclimate
       - task: :docker:test:gitlab-runner
 
   verify:
diff --git a/.config/taskfiles/git/Taskfile-gitlab.yml b/.config/taskfiles/git/Taskfile-gitlab.yml
--- a/.config/taskfiles/git/Taskfile-gitlab.yml
+++ b/.config/taskfiles/git/Taskfile-gitlab.yml
@@ -15,7 +15,7 @@ tasks:
         sh: glab api projects/:fullpath | jq '.id'
       REQUEST_DATA: '{ "name":"PROJECT_CI_ACCESS_TOKEN", "scopes":["write_repository", "read_repository"] }'
       TOKEN_STATUS:
-        sh: glab api projects/:fullpath/access_tokens | jq -r '.[] | select(.name=="PROJECT_CI_ACCESS_TOKENX") | .id'
+        sh: type glab > /dev/null && glab api projects/:fullpath/access_tokens | jq -r '.[] | select(.name=="PROJECT_CI_ACCESS_TOKENX") | .id'
     run: once
     log:
       error: Failed to configure project-specific access token
@@ -66,6 +66,23 @@ tasks:
           glab api projects/:fullpath/protected_branches -X POST -f name=test/windows \
             -f code_owner_approval_required=true -f allow_force_push=true &> /dev/null &
         fi
+        if [[ '{{.REPOSITORY_TYPE}}' == 'packer' ]]; then
+          glab api projects/:fullpath/repository/branches -X POST -f id={{.REPO_ID}} -f branch=hyperv -f ref=master &> /dev/null &
+          glab api projects/:fullpath/protected_branches -X POST -f name=hyperv \
+            -f code_owner_approval_required=true -f allow_force_push=true &> /dev/null &
+          glab api projects/:fullpath/repository/branches -X POST -f id={{.REPO_ID}} -f branch=kvm -f ref=master &> /dev/null &
+          glab api projects/:fullpath/protected_branches -X POST -f name=kvm \
+            -f code_owner_approval_required=true -f allow_force_push=true &> /dev/null &
+          glab api projects/:fullpath/repository/branches -X POST -f id={{.REPO_ID}} -f branch=parallels -f ref=master &> /dev/null &
+          glab api projects/:fullpath/protected_branches -X POST -f name=parallels \
+            -f code_owner_approval_required=true -f allow_force_push=true &> /dev/null &
+          glab api projects/:fullpath/repository/branches -X POST -f id={{.REPO_ID}} -f branch=virtualbox -f ref=master &> /dev/null &
+          glab api projects/:fullpath/protected_branches -X POST -f name=virtualbox \
+            -f code_owner_approval_required=true -f allow_force_push=true &> /dev/null &
+          glab api projects/:fullpath/repository/branches -X POST -f id={{.REPO_ID}} -f branch=vmware -f ref=master &> /dev/null &
+          glab api projects/:fullpath/protected_branches -X POST -f name=vmware \
+            -f code_owner_approval_required=true -f allow_force_push=true &> /dev/null &
+        fi
         wait
 
   create:
@@ -96,9 +113,10 @@ tasks:
           NO_PROMPT=1 glab repo create '{{.GITLAB_PATH}}' --group '{{.GITLAB_GROUP}}' \
           --description '{{.EMOJI_START}}{{.DESCRIPTION}}{{.EMOJI_END}}' --name '{{.NAME}}' \
           {{.PROJECT_TYPE}} --tag "$(jq -r '.keywords | tostring' package.json | sed 's/\[//' | sed 's/\]//')"
+          task --list > /dev/null || (echo "ERROR: Invalid Taskfiles!" && exit 1)
           git add --all
           HUSKY=0 git commit --quiet -m "🎂 Birth" -n || true
-          git push --quiet -u --no-progress gitlab master
+          git push gitlab master
         ignore_error: true
     status:
       - '[ -z "$GITLAB_TOKEN" ] || (test -d .git && glab repo view "{{.GITLAB_PATH}}" > /dev/null)'
@@ -312,6 +330,30 @@ tasks:
       - sh: '[ ! -z "$GITLAB_TOKEN" ]'
         msg: The `GITLAB_TOKEN` environment variable must be set to run this task
 
+  protected:off:
+    deps:
+      - :install:software:glab
+    vars:
+      BRANCH: '{{if .BRANCH}}{{.BRANCH}}{{else}}{{.CLI_ARGS}}{{end}}'
+    todo: figure out how to do it without deleteing the protection first
+    cmds:
+      - glab api projects/:fullpath/protected_branches/{{.BRANCH}} -X DELETE
+      - glab api projects/:fullpath/protected_branches -X POST -f name={{.BRANCH}} -f allow_force_push=true > /dev/null
+    status:
+      - '[ -z "$GITLAB_TOKEN" ]'
+
+  protected:on:
+    deps:
+      - :install:software:glab
+    vars:
+      BRANCH: '{{if .BRANCH}}{{.BRANCH}}{{else}}{{.CLI_ARGS}}{{end}}'
+    todo: figure out how to do it without deleteing the protection first
+    cmds:
+      - glab api projects/:fullpath/protected_branches/{{.BRANCH}} -X DELETE
+      - glab api projects/:fullpath/protected_branches -X POST -f name={{.BRANCH}} -f allow_force_push=false > /dev/null
+    status:
+      - '[ -z "$GITLAB_TOKEN" ]'
+
   update:
     deps:
       - access-token
@@ -322,6 +364,9 @@ tasks:
       - pipelines
       - update:meta
       - wiki
+    run: once
+    status:
+      - '[ -z "$GITLAB_TOKEN" ] || ! type glab &> /dev/null'
 
   update:meta:
     deps:
diff --git a/.config/taskfiles/git/Taskfile.yml b/.config/taskfiles/git/Taskfile.yml
--- a/.config/taskfiles/git/Taskfile.yml
+++ b/.config/taskfiles/git/Taskfile.yml
@@ -4,7 +4,7 @@ version: '3'
 vars:
   EMOJI_END:
     sh: |
-      if [ -f '.variables.json' ]; then
+      if [ -f '.variables.json' ] && type jq &> /dev/null; then
         BP_END="$(jq -r '.emoji_end' .variables.json)"
         if [ "$BP_END" != 'null' ]; then
           echo "$BP_END"
@@ -18,7 +18,7 @@ vars:
       fi
   EMOJI_START:
     sh: |
-      if [ -f '.variables.json' ]; then
+      if [ -f '.variables.json' ] && type jq &> /dev/null; then
         BP_START="$(jq -r '.emoji_start' .variables.json)"
         if [ "$BP_START" != 'null' ]; then
           echo "$BP_START"
@@ -40,11 +40,14 @@ env:
 
 tasks:
   commit:automated:
+    deps:
+      - remotes
     log:
       start: Running automated commit
     cmds:
       - cmd: |
           if [[ "$FULLY_AUTOMATED_TASKS" == 'true' ]]; then
+            task --list > /dev/null || (echo "ERROR: Invalid Taskfiles!" && exit 1)
             git add --all
             HUSKY=0 git commit -m "☁️ Automation" -n
           fi
@@ -104,7 +107,17 @@ tasks:
         RELATIVE_DIR="$(echo $ROLE_DIR | sed 's@'"$PWD"'/@@')"
         HUSKY=0 git subrepo clone {{.BASENAME}} "$RELATIVE_DIR" -b master
 
+  filter:
+    log:
+      error: Error filtering git history
+      start: Filtering unnecessary items from git history
+      success: Successfully filtered unnecessary items from git history
+    cmds:
+      - git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch -r **/node_modules/' --prune-empty -- --all
+
   push:all:
+    deps:
+      - :ci:commit:config
     log:
       error: Encountered error while running `git push all master --force || git push origin master`
       start: Running `git push all master --force || git push origin master`
@@ -114,6 +127,8 @@ tasks:
         if [[ "$FULLY_AUTOMATED_TASKS" == 'true' ]]; then
           git push all master --force || git push origin master
         fi
+    status:
+      - '[ -n "$CI" ]'
 
   remotes:
     deps:
@@ -177,9 +192,9 @@ tasks:
           .config/log success 'Added git remote named `all`'
         fi
     status:
-      - '[[ "$(git config remote.all.url)" == "${GITLAB_REPO}.git" ]] || [[ "${container:=}" == "docker" ]]'
-      - '[[ "$(git config remote.github.url)" == "${GITHUB_REPO}.git" ]] || [[ "${container:=}" == "docker" ]]'
-      - '[[ "$(git config remote.gitlab.url)" == "${GITLAB_REPO}.git" ]] || [[ "${container:=}" == "docker" ]]'
+      - '[[ "$(git config remote.all.url)" == "${GITLAB_REPO}.git" ]] || [ -n "$CI" ]'
+      - '[[ "$(git config remote.github.url)" == "${GITHUB_REPO}.git" ]] || [ -n "$CI" ]'
+      - '[[ "$(git config remote.gitlab.url)" == "${GITLAB_REPO}.git" ]] || [ -n "$CI" ]'
 
   remove:history:cli:
     deps:
@@ -251,18 +266,16 @@ tasks:
         fi
 
   update:
+    run: once
     cmds:
       - task: :git:gitlab:create
       - task: :git:github:create
       - task: update:continue
+    status:
+      - '[ -n "$CI" ]'
 
   update:continue:
     deps:
       - :git:gitlab:update
       - :git:github:update
-    cmds:
-      - |
-        if ! git push -u origin master; then
-          git pull origin master --allow-unrelated-histories
-          git push origin -u origin master
-        fi
+    run: once
diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -16,7 +16,9 @@ includes:
   ci:github: ./.config/taskfiles/ci/Taskfile-github.yml
   common: ./.config/taskfiles/common/Taskfile.yml
   common:code: ./.config/taskfiles/common/Taskfile-code.yml
+  common:start: ./.config/taskfiles/common/Taskfile-start.yml
   common:update: ./.config/taskfiles/common/Taskfile-update.yml
+  common:util: ./.config/taskfiles/common/Taskfile-util.yml
   docker: ./.config/taskfiles/docker/Taskfile.yml
   docker:build: ./.config/taskfiles/docker/Taskfile-build.yml
   docker:test: ./.config/taskfiles/docker/Taskfile-test.yml
@@ -25,16 +27,20 @@ includes:
   git: ./.config/taskfiles/git/Taskfile.yml
   git:github: ./.config/taskfiles/git/Taskfile-github.yml
   git:gitlab: ./.config/taskfiles/git/Taskfile-gitlab.yml
+  git:gitomatic: ./.config/taskfiles/git/Taskfile-gitomatic.yml
   git:hook: ./.config/taskfiles/git/Taskfile-hook.yml
   go: ./.config/taskfiles/go/Taskfile.yml
   go:goreleaser: ./.config/taskfiles/go/Taskfile-goreleaser.yml
   go:test: ./.config/taskfiles/go/Taskfile-test.yml
   image: ./.config/taskfiles/image/Taskfile.yml
   install: ./.config/taskfiles/install/Taskfile.yml
+  install:ansible: ./.config/taskfiles/install/Taskfile-ansible.yml
   install:apt: ./.config/taskfiles/install/Taskfile-apt.yml
+  install:gh: ./.config/taskfiles/install/Taskfile-gh.yml
   install:github: ./.config/taskfiles/install/Taskfile-github.yml
   install:go: ./.config/taskfiles/install/Taskfile-go.yml
   install:npm: ./.config/taskfiles/install/Taskfile-npm.yml
+  install:pipx: ./.config/taskfiles/install/Taskfile-pipx.yml
   install:python: ./.config/taskfiles/install/Taskfile-python.yml
   install:rust: ./.config/taskfiles/install/Taskfile-rust.yml
   install:software: ./.config/taskfiles/install/Taskfile-software.yml
@@ -46,14 +52,12 @@ includes:
   log: ./.config/taskfiles/log/Taskfile.yml
   nest: ./.config/taskfiles/nest/Taskfile.yml
   npm: ./.config/taskfiles/npm/Taskfile.yml
+  npm:bundle: ./.config/taskfiles/npm/Taskfile-bundle.yml
   npm:cov: ./.config/taskfiles/npm/Taskfile-cov.yml
   npm:doc: ./.config/taskfiles/npm/Taskfile-doc.yml
   packer: ./.config/taskfiles/packer/Taskfile.yml
   packer:build: ./.config/taskfiles/packer/Taskfile-build.yml
   packer:update: ./.config/taskfiles/packer/Taskfile-update.yml
-  project:
-    taskfile: ./local/Taskfile-project.yml
-    optional: true
   publish: ./.config/taskfiles/publish/Taskfile.yml
   publish:android: ./.config/taskfiles/publish/Taskfile-android.yml
   publish:brew: ./.config/taskfiles/publish/Taskfile-brew.yml
@@ -68,12 +72,15 @@ includes:
   release: ./.config/taskfiles/release/Taskfile.yml
   security: ./.config/taskfiles/security/Taskfile.yml
   symlink: ./.config/taskfiles/symlink/Taskfile.yml
+  ui: ./.config/taskfiles/ui/Taskfile.yml
+  update: ./.config/taskfiles/update/Taskfile.yml
   upstream: ./.config/taskfiles/upstream/Taskfile.yml
   upstream:common: ./.config/taskfiles/upstream/Taskfile-common.yml
   upstream:commondocs: ./.config/taskfiles/upstream/Taskfile-commondocs.yml
   upstream:docs: ./.config/taskfiles/upstream/Taskfile-docs.yml
   upstream:project: ./.config/taskfiles/upstream/Taskfile-project.yml
   upstream:shared: ./.config/taskfiles/upstream/Taskfile-shared.yml
+  vagrant: ./.config/taskfiles/vagrant/Taskfile.yml
   vscode: ./.config/taskfiles/vscode/Taskfile.yml
   web: ./.config/taskfiles/web/Taskfile.yml
   web:ionic: ./.config/taskfiles/web/Taskfile-ionic.yml
@@ -83,34 +90,130 @@ includes:
 output: interleaved
 
 vars:
-  DOCKERHUB_PROFILE: megabytelabs
-  DOCKERHUB_USER: professormanhattan
+  DOCKERHUB_PROFILE:
+    sh: |
+      if [ -f .config/variables.json ] && type jq &> /dev/null; then
+        echo "$(jq -r '.profile.dockerhub' .config/variables.json)"
+      else
+        echo 'megabytelabs'
+      fi
+  DOCKERHUB_USER:
+    sh: |
+      if [ -f .config/variables.json ] && type jq &> /dev/null; then
+        echo "$(jq -r '.profile.dockerHubUser' .config/variables.json)"
+      else
+        echo 'ProfessorManhattan'
+      fi
   ESLINT_FIX_RECURSIVE: 'true'
   ESLINT_FORMATTER: stylish
   ESLINT_FORMATTER_OPTIONS: git-log gitlab pretty summary
-  GALAXY_NAMESPACE: professormanhattan
-  GITHUB_ORG: ProfessorManhattan
-  GITHUB_USER: ProfessorManhattan
+  GALAXY_AUTHOR: ProfessorManhattan
+  GALAXY_COMPANY: Megabyte Labs
+  GALAXY_NAMESPACE:
+    sh: |
+      if [ -f meta/main.yml ]; then
+        grep namespace < meta/main.yml | sed 's/.*namespace: \\(.*\\)$/\\1/g'
+      else
+        if [ -f .config/variables.json ] && type jq &> /dev/null; then
+          echo "$(jq -r '.profile.galaxy' .config/variables.json)"
+        else
+          echo 'ProfessorManhattan'
+        fi
+      fi
+  GALAXY_ROLE_NAME:
+    sh: "if [ -f meta/main.yml ]; then grep role_name < meta/main.yml | sed 's/.*role_name: \\(.*\\)$/\\1/g'; fi"
+  GITHUB_ORG:
+    sh: |
+      if [ -f .config/variables.json ] && type jq &> /dev/null; then
+         echo "$(jq -r '.profile.githubOrg' .config/variables.json)"
+      else
+        echo 'megabyte-labs'
+      fi
+  GITHUB_USER:
+    sh: |
+      if [ -f .config/variables.json ] && type jq &> /dev/null; then
+         echo "$(jq -r '.profile.github' .config/variables.json)"
+      else
+        echo 'ProfessorManhattan'
+      fi
   GROUP_EXEC_ASYNC: 'false'
-  IGNORE_FOLDERS: -path './.autodoc/*' -o -path './.cache/*' -o -path './.common*' -o -path './.config/*' -o -path './.git/*'
-    -o -path './.github/*' -o -path './.gitlab/*' -o -path './.husky/*' -o -path './.modules/*' -o -path './.npm/*'
-    -o -path './.pnpm-store/*' -o -path './.shared/*' -o -path './.task/*' -o -path './.venv/*' -o -path './.vscode/*'
-    -o -path './build/*' -o -path './dist/*' -o -path './node_modules/*' -o -path './roles/*' -o -name pnpm-lock.yaml
-    -o -name package-lock.json -o -name poetry.lock -o -name '.variables.json'
+  # yamllint disable rule:line-length
+  IGNORE_FOLDERS: >-
+    -path './.autodoc/*' -o -path './.cache/*' -o -path './.common*' -o -path './.config/*' -o -path './.git/*' -o
+    -path './.modules/*' -o -path './.npm/*' -o
+    -path './.pnpm-store/*' -o -path './.shared/*' -o -path './.task/*' -o -path './.venv/*' -o -path './.vscode/*' -o
+    -path './build/*' -o -path './dist/*' -o -path './node_modules/*' -o -path './roles/*' -o -name pnpm-lock.yaml -o
+    -name package-lock.json -o -name poetry.lock -o -name '.variables.json' -o -name '.git'
   INIT_SCRIPT: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/scripts/update-init.sh
   LOG_FIX:
-    sh: chmod +x .config/log && echo "heyhey"
+    sh: chmod +x .config/log
   MODEL_TASKFILE: https://gitlab.com/megabyte-labs/common/shared/-/raw/master/Taskfile.yml
-  NPM_KEEP_UPDATED: glob
+  NPM_KEEP_UPDATED: ''
   NPM_PROGRAM: npm
-  NPM_PROGRAM_LOCAL: pnpm
-  NPX_HANDLE: 'pnpx '
-  NPX_PACKAGE: pnpx
-  PROJECT_TYPE: project
-  PYTHON_HANDLE: 'poetry run '
+  NPM_PROGRAM_LOCAL:
+    sh: |
+      if type pnpm &> /dev/null; then
+        echo 'pnpm'
+      elif type npm &> /dev/null; then
+        echo 'npm'
+      fi
+  NPX_HANDLE:
+    sh: |
+      if type pnpx &> /dev/null; then
+        echo 'pnpx '
+      elif type pnpm &> /dev/null; then
+        echo 'pnpm '
+      fi
+  PROJECT_TYPE:
+    sh: |
+      if type jq &> /dev/null && [ -f package.json ]; then VER="$(jq -r '.blueprint.group' package.json)"; if [ "$VER" == 'null' ]; then echo TYPE="$GROUP_TYPE"; else TYPE="$VER"; fi; else TYPE="$GROUP_TYPE"; fi
+      if type jq &> /dev/null && [ -f package.json ]; then VER="$(jq -r '.blueprint.subgroup' package.json)"; if [ "$VER" == 'null' ]; then SUBTYPE="$REPOSITORY_TYPE"; else SUBTYPE="$VER"; fi; else SUBTYPE="$REPOSITORY_TYPE"; fi
+      if [ "$TYPE" == 'common' ] && [ "$SUBTYPE" == 'shared' ]; then
+        echo 'shared'
+      elif [ "$TYPE" == 'common' ]; then
+        echo 'common'
+      elif [ "$TYPE" == 'documentation' ] && [ "$SUBTYPE" == 'shared' ]; then
+        echo 'commondocs'
+      elif [ "$TYPE" == 'documentation' ]; then
+        echo 'docs'
+      else
+        echo 'project'
+      fi
+  # yamllint enable rule:line-length
+  PYTHON_HANDLE:
+    sh: |
+      if type poetry &> /dev/null; then
+        echo 'poetry run '
+      else
+        echo ''
+      fi
   PYTHON_VIRTUALENV: true
-  REPOSITORY_SUBTYPE: playbook
-  REPOSITORY_TYPE: ansible
+  REPOSITORY_SUBTYPE:
+    sh: |
+      if [ -n "$REPOSITORY_TYPE" ]; then REPO_SUBTYPE="$REPOSITORY_TYPE"; fi
+      if type jq &> /dev/null && [ -f package.json ]; then
+        VER="$(jq -r '.blueprint.subgroup' package.json)"
+        if [ "$VER" == 'null' ]; then
+          if [ -n "$REPO_SUBTYPE" ]; then echo "$REPO_SUBTYPE"; else echo "misc"; fi
+        else
+          echo "$VER"
+        fi
+      else
+        if [ -n "$REPO_SUBTYPE" ]; then echo "$REPO_SUBTYPE"; else echo "misc"; fi
+      fi
+  REPOSITORY_TYPE:
+    sh: |
+      if [ -n "$GROUP_TYPE" ]; then REPO_TYPE="$GROUP_TYPE"; fi
+      if type jq &> /dev/null && [ -f package.json ]; then
+        VER="$(jq -r '.blueprint.group' package.json)"
+        if [ "$VER" == 'null' ]; then
+          if [ -n "$REPO_TYPE" ]; then echo "$REPO_TYPE"; else echo "misc"; fi
+        else
+          echo "$VER"
+        fi
+      else
+        if [ -n "$REPO_TYPE" ]; then echo "$REPO_TYPE"; else echo "misc"; fi
+      fi
   SEMANTIC_CONFIG: semantic-release-config
   TIMEZONE: America/New_York
 
@@ -121,7 +224,14 @@ env:
       LIBC=$(ldd /bin/ls | grep 'musl' | head -1 | cut -d ' ' -f1)
       if [ -n "$LIBC" ]; then LINUX_FLAVOR='linux-musl'; fi{{end}}
       echo "{{if (eq OS "linux")}}$LINUX_FLAVOR{{else}}darwin{{end}}"
-  SENTRY_DSN: https://glet_eba773e2329ceebd1c8a3de52dc3420d@gitlab.com/api/v4/error_tracking/collector/18473622
+  RECORD_INSTALL:
+    sh: if [ -n "$CI" ]; then echo 'true'; fi
+  SENTRY_DSN:
+    sh: |
+      if type jq &> /dev/null; then
+        DSN="$(jq -r '.blueprint.sentryDSN' package.json)"
+        if [ "$DSN" != 'null' ]; then echo "$DSN"; fi
+      fi
 
 profile: |
   PATH="$PATH:$HOME/.local/bin:$HOME/.poetry/bin"
@@ -163,7 +273,11 @@ tasks:
     cmds:
       - |
         if [ "$(jq '.scripts.build' package.json)" != 'null' ]; then
-          npm run build
+          if type npm &> /dev/null; then
+            npm run build
+          else
+            task {{.REPOSITORY_TYPE}}:build
+          fi
         else
           [[ $- == *i* ]] && task prepare || (.config/log error '{{.NONINTERACTIVE_MISSING_BUILD_CMD}}' && exit 1)
         fi
@@ -231,18 +345,29 @@ tasks:
     cmds:
       - |
         {{if .CLI_ARGS}}
+        task --list > /dev/null || (echo "ERROR: Invalid Taskfiles!" && exit 1)
         git add --all
         HUSKY=0 git commit -m "{{.CLI_ARGS}}" --no-verify
         {{else}}
+        task --list > /dev/null || (echo "ERROR: Invalid Taskfiles!" && exit 1)
         git add --all
         git commit
         {{end}}
 
   commit:quick:
+    deps:
+      - ci:commit:config
     cmds:
-      - git add --all
+      - |
+        task --list > /dev/null || (echo "ERROR: Invalid Taskfiles!" && exit 1)
+        git add --all
       - HUSKY=0 git commit -m '🔧 chore(tweak): quick minor update' --no-verify
       - git push origin master
+
+  devcontainer:
+    deps:
+      - install:npm:devcontainer
+      - install:software:docker
 
   donothing: 'true'
 
@@ -278,6 +403,19 @@ tasks:
     cmds:
       - task: fix:all
 
+  get:links:
+    deps:
+      - install:software:jq
+    desc: Log useful links such as the current project's git repository link
+    vars:
+      GITHUB_URL:
+        sh: jq -r '.blueprint.repository.github' package.json
+      GITLAB_URL:
+        sh: jq -r '.blueprint.repository.gitlab' package.json
+    cmds:
+      - .config/log info 'GitHub -----> `{{.GITHUB_URL}}`'
+      - .config/log info 'GitLab -----> `{{.GITLAB_URL}}`'
+
   group:exec:
     desc: Execute group commands on any GitLab group (including repositories in sub-groups)
     summary: |
@@ -305,10 +443,9 @@ tasks:
       - install:software:yq
     desc: Runs the initialization script
     summary: |
-      # Initialize the Project and Run the Full Update Sequence
+      # Initialize the Project
 
-      This command will mostly not be needed for pre-existing projects. This task begins
-      by calling a script that:
+      This command will mostly not be needed for pre-existing projects. This task:
 
       1. Migrates legacy projects
       2. Fixes common errors
@@ -330,17 +467,8 @@ tasks:
       success: Successfully bootstrapped project by running initialization script
     cmds:
       - git init
-      - |
-        TMP="$(mktemp)" && curl -sSL {{.MODEL_TASKFILE}} > "$TMP"
-        .config/log info 'Ensuring new additions to the model `Taskfile.yml` are present in the project `Taskfile.yml`'
-        yq eval-all -i 'select(fileIndex == 0) * select(fileIndex == 1)' "$TMP" Taskfile.yml
-      - |
-        if [ -n "$UPDATE_INIT_SCRIPT" ]; then
-          bash <(curl -sSL "$UPDATE_INIT_SCRIPT")
-        else
-          bash <(curl -sSL {{.INIT_SCRIPT}})
-        fi
-      - git push origin master
+      - task: repair
+      - task: prepare
 
   lint:
     desc: Lints the project using all linters
@@ -396,6 +524,11 @@ tasks:
         fi
       - nodemon --config {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.config/nodemon.json{{end}}
 
+  new:project:
+    desc: Create a new project
+    cmds:
+      - task: prepare
+
   playbook:
     desc: Run the playbook
     summary: |
@@ -449,7 +582,9 @@ tasks:
       start: Preloading system with common dependencies
       success: Successfully preloaded system with common dependencies (REBOOT RECOMMENDED)
     cmds:
+      - task: install:software:common
       - task: install:brewfile
+      - task: install:extras
       - task: install:go:bundle
       - task: install:rust:bundle
       - task: install:github:bundle
@@ -552,6 +687,33 @@ tasks:
         HUSKY=0 git commit -a --allow-empty -m '🔨 build(version bump): semantic-release {{.UPDATE_LEVEL}}' -n
       - task: publish
 
+  pull:upstream:
+    desc: Pull from upstream repositories
+    summary: |
+      # Pull Changes from Upstream Repositories
+
+      This task will do a `git pull` on each repository defined in `.blueprint.upstreamRemotes`.
+      The variable should be an array of objects where each object has the `remote`, `url`, and `branch` keys.
+
+      **Sample value of `.blueprint.upstreamRemotes`:**
+      `[{ "remote": "ionic", "url": "git@github.com:ionic-team/ionic-docs.git", "branch": "main" }]`
+    log:
+      error: Encountered error while running `git pull` on each of the `upstreamRemotes`
+      start: Running `git pull` on each of the `upstreamRemotes`
+      success: Successfully pulled from `upstreamRemotes`
+    cmds:
+      - task: common:update:upstream:remotes:pull
+
+  repair:
+    cmds:
+      - task: common:repair
+      - |
+        if [ -n "$UPDATE_INIT_SCRIPT" ]; then
+          bash <(curl -sSL "$UPDATE_INIT_SCRIPT")
+        else
+          bash <(curl -sSL {{.INIT_SCRIPT}})
+        fi
+
   reset:
     desc: Resets the project by removing all caches and then re-generating templated files
     summary: |
@@ -649,6 +811,30 @@ tasks:
       - task: common:shell
 
   start:
+    desc: Start the project by installing / updating dependencies, repairing issues, and opening a tutorial
+    summary: |
+      # Start the Project
+
+      This task does everything that running `bash start.sh` does plus a little bit more:
+
+      1. Installs Homebrew if it is not already installed
+      2. Ensures Bodega is installed and up-to-date
+      3. Ensures common system dependencies and runtimes
+      4. Installs commonly used CLI tools
+      5. Ensures local dependencies such as `node_modules` are installed
+      6. Attempts to repair the project if it detects any issues
+
+      It basically sets up all the tools you need, in advance so that problems can be detected as early
+      as possible. In some cases, this command will open documentation or a tutorial to read while dependencies are being
+      installed.
+    log:
+      error: Yikes! Error starting the project!
+      start: Starting the project..
+      success: Project started!
+    cmds:
+      - task: common:start
+
+  synchronize:
     desc: Set up the project and refresh it with the latest changes
     summary: |
       # Start the Project
@@ -667,10 +853,62 @@ tasks:
       start: Synchronizing project with upstream file changes and bootstrapping
       success: Successfully synchronized the project with upstream file changes and also bootstrapped the project
     cmds:
-      - task: upstream:project
+      - task: upstream:{{.PROJECT_TYPE}}
+
+  tag:deps:
+    desc: Inject a new command in the `Taskfile.yml` that includes all tasks matching a given tag as deps
+    summary: |
+      # Create Task with Deps Based on Tag
+
+      Use this task to inject a new task in the `Taskfile.yml` that includes all the tasks
+      that are tagged with a certain tag as deps. The tag must be supplied as a CLI argument.
+
+      Say you have a task that looks like this:
+
+      ```
+      my-task:
+        tags:
+          - docker
+        cmds:
+          - docker volume ls
+      ```
+
+      Then, by running `task tag:deps -- docker`, you will get the following task injected into the
+      `Taskfile.yml` file:
+
+      ```
+      deps:docker:
+        deps:
+          - my-task
+      ```
+    cmds:
+      - task: common:util:task:tag:deps
+
+  template:
+    deps:
+      - install:npm:liquidjs
+    summary: |
+      # Render a Template
+
+      This task is provided to serve as an alias for developing new templated files.
+    cmds:
+      - |
+        function handlebars() {
+          FILE="$1"
+          TMP="$(mktemp)"
+          .config/log info 'Generating `'"${FILE//.liquid}"'` from `'"$FILE"'`'
+          {{.NPX_HANDLE}}hbs --data .variables.json --helper ./.config/hbs.cjs "$FILE" --stdout > "$TMP"
+          mv "$TMP" "${FILE//.liquid}"
+          rm "$FILE"
+        }
+        handlebars '{{.CLI_ARGS}}'
+    preconditions:
+      - sh: test -f .variables.json
+        msg: This task requires that you have already spun up the project by running `task start`
 
   test:
     deps:
+      - install:software:jq
       - install:software:node
     interactive: true
     desc: Open an interactive dialog to select and run a Molecule test
@@ -698,3 +936,31 @@ tasks:
         else
           [[ $- == *i* ]] && task prepare || (.config/log error '{{.NONINTERACTIVE_MISSING_TEST_CMD}}' && exit 1)
         fi
+
+  update:
+    desc: Fully update the repository
+    summary: |
+      # Update the Repository / Project
+
+      This task will:
+
+      1. Ensure Homebrew is installed
+      2. Ensure runtimes like Node.js, Go, Python, and Poetry are installed
+      3. Ensure the `PATH` environment variable is properly configured
+      4. Configure the environment if it is in a `$CI` environment
+      5. Run a repair script that is used to ensure older repositories are compatible with the Taskfile scripts
+      6. Prepare the repository by automatically setting up certain parts of the project
+      7. Run a full update on the repository with `task start`
+      8. Automatically commit changes
+      9. Update GitLab/GitHub repository settings if the `GITHUB_TOKEN` / `GITLAB_TOKEN` variables are set
+
+      Along the way, if any dependencies are missing they will be installed as well just like with all of the
+      tasks included in these Taskfiles.
+    log:
+      error: Failed to update the repository
+      start: Updating the repository..
+      success: Finished updating the repository
+    cmds:
+      - task: common:start
+        env:
+          UPDATE_PROJECT: 'true'
