Update roles/misc/qubes/handlers/main.yml, roles/misc/qubes/tasks/theme.yml
Former-commit-id: c175420dc0a63438032075ebb5dec3c2c7266deb

diff --git a/roles/misc/qubes/tasks/theme.yml b/roles/misc/qubes/tasks/theme.yml
--- a/roles/misc/qubes/tasks/theme.yml
+++ b/roles/misc/qubes/tasks/theme.yml
@@ -39,6 +39,34 @@
     dest: /usr/share/
     remote_src: true
 
+- name: Ensure /usr/share/plasma uses files instead of symlinks
+  become: true
+  shell:
+    cmd: |
+      set -e
+      function squashSymlink() {
+        for link; do
+          test -h "$link" || continue
+
+          dir=$(dirname "$link")
+          reltarget=$(readlink "$link")
+          case $reltarget in
+              /*) abstarget=$reltarget;;
+              *)  abstarget=$dir/$reltarget;;
+          esac
+
+          rm -fv "$link"
+          cp -afv "$abstarget" "$link" || {
+              # on failure, restore the symlink
+              rm -rfv "$link"
+              ln -sfv "$reltarget" "$link"
+          }
+        done
+      }
+      find /usr/share/plasma -type l -exec squashSymlink {} +
+  register: squash_symlink
+  changed_when: "squash_symlink.stdout != ''"
+
 - name: Ensure dependencies are installed
   include_tasks: dependency.yml
   loop:
