Update roles/misc/qubes/tasks/theme.yml
Former-commit-id: 14e050162d249a8f4ba47a8ba0d41417a1aba2b2

diff --git a/roles/misc/qubes/tasks/theme.yml b/roles/misc/qubes/tasks/theme.yml
--- a/roles/misc/qubes/tasks/theme.yml
+++ b/roles/misc/qubes/tasks/theme.yml
@@ -50,27 +50,22 @@
   become: true
   shell:
     cmd: |
-      set -e
-      function squashSymlink() {
-        for link; do
-          test -h "$link" || continue
-
-          dir=$(dirname "$link")
-          reltarget=$(readlink "$link")
-          case $reltarget in
-              /*) abstarget=$reltarget;;
-              *)  abstarget=$dir/$reltarget;;
-          esac
-
-          rm -fv "$link"
-          cp -afv "$abstarget" "$link" || {
-              # on failure, restore the symlink
-              rm -rfv "$link"
-              ln -sfv "$reltarget" "$link"
-          }
-        done
-      }
-      find /usr/share/plasma -type l -exec squashSymlink {} +
+      set -ex
+      while read link; do
+        test -h "$link" || continue
+        dir=$(dirname "$link")
+        reltarget=$(readlink "$link")
+        case $reltarget in
+            /*) abstarget=$reltarget;;
+            *)  abstarget=$dir/$reltarget;;
+        esac
+        rm -fv "$link"
+        cp -afv "$abstarget" "$link" || {
+            # on failure, restore the symlink
+            rm -rfv "$link"
+            ln -sfv "$reltarget" "$link"
+        }
+      done< <(find /usr/share/plasma -type l)
   register: squash_symlink
   changed_when: "squash_symlink.stdout != ''"
   args:
