🔧 chore(latest): latest

diff --git a/roles/applications/androidstudio/.config/taskfiles/fix/Taskfile.yml b/roles/applications/androidstudio/.config/taskfiles/fix/Taskfile.yml
--- a/roles/applications/androidstudio/.config/taskfiles/fix/Taskfile.yml
+++ b/roles/applications/androidstudio/.config/taskfiles/fix/Taskfile.yml
@@ -23,6 +23,7 @@ tasks:
     deps:
       - :install:modules:local
       - :install:npm:eslint
+      - :install:software:expect
     desc: Fix JavaScript/TypeScript errors automatically
     hide: '{{not (has .REPOSITORY_TYPE (list "angular" "npm"))}}'
     summary: |
@@ -42,8 +43,23 @@ tasks:
       start: Auto-fixing with ESLint
       success: ESLint fixing appears to have corrected all the issues {{if .CLI_ARGS}}in `{{.CLI_ARGS}}`{{else}}in the project{{end}}
     cmds:
-      - '{{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format pretty --cache --cache-location .cache/eslintcache
-        --fix {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+      - 'unbuffer {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache --cache-location .cache/eslintcache
+        --fix {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} | tee eslint.log'
+      - |
+        if [ '{{.ESLINT_FIX_RECURSIVE}}' == 'true' ]; then
+          COUNT=0
+          while [ $COUNT -le 5 ]; do
+            COUNT=$((COUNT + 1))
+            if grep 'potentially fixable with the `--fix` option' < eslint.log > /dev/null; then
+              COUNT="$COUNT"
+              unbuffer {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache --cache-location .cache/eslintcache \
+              --fix {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} | tee eslint.log
+            else
+              echo '' > eslint.log
+            fi
+          done
+        fi
+      - rm eslint.log
 
   go:
     desc: Fix Go with all available Go fixers
@@ -226,7 +242,12 @@ tasks:
     log:
       start: Running Prettier on {{if .CLI_ARGS}}`{{.CLI_ARGS}}`{{else}}project{{end}}
     cmds:
-      - '{{.NPX_HANDLE}}prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+      - |
+        {{.NPX_HANDLE}}prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} || EXIT_CODE=$?
+        if [ -n "$EXIT_CODE" ]; then
+          .config/log warn 'Failed to run `{{.NPX_HANDLE}}prettier` - falling back to `prettier`'
+          prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --write {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
+        fi
 
   python:
     deps:
@@ -303,6 +324,35 @@ tasks:
         {{else}}
           find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.sh' -o -name '*.sh.j2' \) \
             -print0 | xargs -0 {{.NPX_HANDLE}}shellcheck -e {{.SHELLCHECK_EXCLUDE}} -f diff | git apply
+        {{end}}
+
+  toml:
+    deps:
+      - :install:python:requirements
+    desc: Format `.toml` files by alphabetizing and flattening
+    summary: |
+      # Automatically format `.toml` files
+
+      [toml-sort](https://pypi.org/project/toml-sort/) will automatically alphabetize and flatten
+      `.toml` files.
+
+      **Example running on whole project:**
+      `task fix:toml`
+
+      **Example usage on specific file:**
+      `task fix:toml -- pyproject.toml`
+    log:
+      error: Encountered an error while running `toml-sort`
+      start: Running `toml-sort` auto-fixer
+      success: Successfully ran the `toml-sort` auto-fixer
+    cmds:
+      - |
+        {{if .CLI_ARGS}}
+          {{.PYTHON_HANDLE}}toml-sort -i --all {{.CLI_ARGS}}
+        {{else}}
+          while read PATHH; do
+            {{.PYTHON_HANDLE}}toml-sort -i --all "$PATHH"
+          done < <(find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.toml' \))
         {{end}}
 
   xml:
