☁️ chore(automation): Applying changes from upstream repository.

diff --git a/.config/taskfiles/install/Taskfile-software.yml b/.config/taskfiles/install/Taskfile-software.yml
--- a/.config/taskfiles/install/Taskfile-software.yml
+++ b/.config/taskfiles/install/Taskfile-software.yml
@@ -1087,28 +1087,38 @@ tasks:
   system:
     vars:
       PACKAGE: '{{if .PACKAGE}}{{.PACKAGE}}{{else}}{{.CLI_ARGS}}{{end}}'
-    log:
-      error: Failed to install `{{.PACKAGE}}` with the system package manager
-      start: Attempting to install `{{.PACKAGE}}` using the system package manager
     cmds:
-      - task: system:apk
-        vars:
-          PACKAGE: '{{.PACKAGE}}'
-      - task: system:apt-get
-        vars:
-          PACKAGE: '{{.PACKAGE}}'
-      - task: system:dnf
-        vars:
-          PACKAGE: '{{.PACKAGE}}'
-      - task: system:pacman
-        vars:
-          PACKAGE: '{{.PACKAGE}}'
-      - task: system:yum
-        vars:
-          PACKAGE: '{{.PACKAGE}}'
-      - task: system:macos
-        vars:
-          PACKAGE: '{{.PACKAGE}}'
+      - .config/log start 'Attempting to install `{{.PACKAGE}}` using the system package manager'
+      - |
+        if [ -f "/etc/redhat-release" ]; then
+          if type dnf &> /dev/null; then
+            task install:software:system:dnf -- '{{.PACKAGE}}'
+          else
+            task install:software:system:yum -- '{{.PACKAGE}}'
+          fi
+        elif [ -f "/etc/debian_version" ]; then
+          task install:software:system:apt-get -- '{{.PACKAGE}}'
+        elif [ -f "/etc/arch-release" ]; then
+          task install:software:system:pacman -- '{{.PACKAGE}}'
+        elif [ -f "/etc/alpine-release" ]; then
+          task install:software:system:apk -- '{{.PACKAGE}}'
+        elif type dnf &> /dev/null; then
+          task install:software:system:dnf -- '{{.PACKAGE}}'
+        elif type yum &> /dev/null; then
+          task install:software:system:yum -- '{{.PACKAGE}}'
+        elif type apt-get &> /dev/null; then
+          task install:software:system:apt-get -- '{{.PACKAGE}}'
+        elif type pacman &> /dev/null; then
+          task install:software:system:pacman -- '{{.PACKAGE}}'
+        elif type apk &> /dev/null; then
+          task install:software:system:apk -- '{{.PACKAGE}}'
+        else
+          if [ '{{OS}}' == 'darwin' ]; then
+            task install:software:system:macos -- '{{.PACKAGE}}'
+          else
+            .config/log error 'No matching system. Cannot continue with installation.' && exit 1
+          fi
+        fi
     status:
       - type {{.PACKAGE}} > /dev/null || [ '{{.PACKAGE}}' == 'null' ]
 
