Ran mass update with .start.sh.

diff --git a/roles/virtualization/gitdocker/.husky/pre-commit b/roles/virtualization/gitdocker/.husky/pre-commit
--- a/roles/virtualization/gitdocker/.husky/pre-commit
+++ b/roles/virtualization/gitdocker/.husky/pre-commit
@@ -38,13 +38,8 @@ npm run lint
 log "Checking for spelling errors"
 FILES=$(git diff --cached --name-only)
 if [ "$FILES" ]; then
-  SPELLING_ERRORS=$(npx cspell --no-summary --no-progress --show-context --show-suggestions --no-must-find-files --config ./.modules/shared/.cspell.json $FILES)
-  if [ "$SPELLING_ERRORS" ]; then
-    echo $SPELLING_ERRORS
-    warn "Review the list of possible misspelled words above and correct anything that needs changing."
-  else
-    success "No spelling errors were found - good job!"
-  fi
+  npx cspell --no-summary --no-progress --show-context --no-must-find-files --config ./.modules/shared/.cspell.json $FILES || true
+  warn "A spell check was performed - if there are any spelling errors reported above then please fix them prior to committing the code."
 else
   info "No files staged for spell checking"
 fi
