⤵️ chore(synchronize) Applying changes from upstream repository.

diff --git a/.config/husky/pre-commit b/.config/husky/pre-commit
--- a/.config/husky/pre-commit
+++ b/.config/husky/pre-commit
@@ -7,23 +7,37 @@
 if [ -f "$(dirname "$0")/_/husky.sh" ]; then
   . "$(dirname "$0")/_/husky.sh"
 
-  .config/log info "Performing various pre-commit tasks on staged files (like autofixing, detecting private keys, etc.)"
+  # Attempt to register Bodega/Task from common places if it is not in PATH
+  if ! type task &> /dev/null && [ -f "$HOME/.profile" ]; then
+    . "$HOME/.profile"
+  elif ! type task &> /dev/null; then
+    PATH="$PATH:$HOME/.local/go/bin:$HOME/.local/bin:$HOME/bin:$HOME/go/bin"
+  fi
 
-  STAGED_FILES=$(git diff --cached --name-only)
-  for FILE in "$STAGED_FILES"; do
-    if [ -f "$1" ]; then
-      type task &> /dev/null && task git:hook:pre-commit -- "$FILE" &
-    fi
-  done
-  wait
 
-  .config/log info 'Linting and fixing the staged files with `lint-staged`'
-  type task &> /dev/null && task lint:lint-staged
+  # Show warning if Bodega/Task is still not registered/installed, else proceed with hook
+  if ! type task &> /dev/null; then
+    .config/log warn 'Bodega `task` does not appear to be installed or is not registered in the `PATH` variable - please manually include it'
+    .config/log info 'Get Bodega here -> `https://github.com/megabyte-labs/Bodega`'
+  else
+    .config/log info "Performing various pre-commit tasks on staged files (like autofixing, detecting private keys, etc.)"
 
-  .config/log info 'Reporting possible spelling errors in the staged files with `cspell`'
-  type task &> /dev/null && task lint:spelling
+    STAGED_FILES=$(git diff --cached --name-only)
+    for FILE in "$STAGED_FILES"; do
+      if [ -f "$1" ]; then
+        type task &> /dev/null && task git:hook:pre-commit -- "$FILE" &
+      fi
+    done
+    wait
 
-  .config/log success 'Pre-commit validation complete!'
+    .config/log info 'Linting and fixing the staged files with `lint-staged`'
+    type task &> /dev/null && task lint:lint-staged
+
+    .config/log info 'Reporting possible spelling errors in the staged files with `cspell`'
+    type task &> /dev/null && task lint:spelling
+
+    .config/log success 'Pre-commit validation complete!'
+  fi
 else
   .config/log warn 'Husky pre-commit hooks are currently not properly setup.'
 fi
