☁️ Automation

diff --git a/roles/languages/deno/.config/taskfiles/install/Taskfile-python.yml b/roles/languages/deno/.config/taskfiles/install/Taskfile-python.yml
--- a/roles/languages/deno/.config/taskfiles/install/Taskfile-python.yml
+++ b/roles/languages/deno/.config/taskfiles/install/Taskfile-python.yml
@@ -76,12 +76,18 @@ tasks:
         if [ -n "$GITLAB_CI" ]; then
           poetry config http-basic.gitlab gitlab-ci-token "${CI_JOB_TOKEN}"
         fi
-      - .config/log info "Installing/updating poetry install options -> {{.INSTALL_OPTIONS}}"
       - |
         if [ -n "$AUTO_UPDATE_PIP_PACKAGES" ]; then
+          .config/log info 'Updating Poetry dependencies{{if .INSTALL_OPTIONS}} with options `{{.INSTALL_OPTIONS}}`{{end}}'
           poetry update{{if .INSTALL_OPTIONS}} {{.INSTALL_OPTIONS}}{{end}}
         else
-          poetry install{{if .INSTALL_OPTIONS}} {{.INSTALL_OPTIONS}}{{end}}
+          .config/log info 'Installing Poetry dependencies{{if .INSTALL_OPTIONS}} with options `{{.INSTALL_OPTIONS}}`{{end}}'
+          poetry install{{if .INSTALL_OPTIONS}} {{.INSTALL_OPTIONS}}{{end}} || EXIT_CODE=$?
+          if [ -n "$EXIT_CODE" ]; then
+            .config/log warn 'Running `poetry install{{if .INSTALL_OPTIONS}} {{.INSTALL_OPTIONS}}{{end}}` failed.'
+            .config/log info 'Attempting to fix by running `poetry update{{if .INSTALL_OPTIONS}} {{.INSTALL_OPTIONS}}{{end}}`'
+            poetry update{{if .INSTALL_OPTIONS}} {{.INSTALL_OPTIONS}}{{end}}
+          fi
         fi
     sources:
       - pyproject.toml
